using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BSDPROJE.Entities.Tables.Views
{
    public class ZZ_BSD_VW_SIPARIS
    {
        public string STOK_KODU { get; set; } //(varchar(35), not null)
        public string FISNO { get; set; } //(varchar(15), not null)
        public decimal STHAR_GCMIK { get; set; } //(decimal(28,8), null)
        public decimal STHAR_GCMIK2 { get; set; } //(decimal(28,8), null)
        public decimal CEVRIM { get; set; } //(decimal(28,14), null)
        public string STHAR_GCKOD { get; set; } //(char(1), not null)
        public DateTime STHAR_TARIH { get; set; } //(datetime, not null)
        public decimal STHAR_NF { get; set; } //(decimal(28,8), null)
        public decimal STHAR_BF { get; set; } //(decimal(28,8), null)
        public decimal STHAR_IAF { get; set; } //(decimal(28,8), null)
        public decimal STHAR_KDV { get; set; } //(decimal(5,2), null)
        public string STHAR_ACIKLAMA { get; set; } //(varchar(35), null)
        public decimal STHAR_SATISK { get; set; } //(decimal(28,8), null)
        public decimal STHAR_MALFISK { get; set; } //(decimal(15,5), null)
        public string STHAR_FTIRSIP { get; set; } //(char(1), not null)
        public decimal STHAR_SATISK2 { get; set; } //(decimal(28,8), null)
        public byte LISTE_FIAT { get; set; } //(tinyint, null)
        public string STHAR_HTUR { get; set; } //(char(1), not null)
        public byte STHAR_DOVTIP { get; set; } //(tinyint, null)
        public byte PROMASYON_KODU { get; set; } //(tinyint, null)
        public decimal STHAR_DOVFIAT { get; set; } //(decimal(28,15), null)
        public decimal STRA_SATISK3 { get; set; } //(decimal(28,8), null)
        public decimal STRA_SATISK4 { get; set; } //(decimal(28,8), null)
        public decimal STRA_SATISK5 { get; set; } //(decimal(28,8), null)
        public decimal STRA_SATISK6 { get; set; } //(decimal(28,8), null)
        public string STHAR_BGTIP { get; set; } //(char(1), null)
        public string STHAR_KOD1 { get; set; } //(char(1), null)
        public string STHAR_KOD2 { get; set; } //(char(1), null)
        public string STHAR_SIPNUM { get; set; } //(varchar(15), null)
        public string STHAR_CARIKOD { get; set; } //(varchar(15), null)
        public string STHAR_SIP_TURU { get; set; } //(char(1), null)
        public string PLASIYER_KODU { get; set; } //(varchar(8), null)
        public string EKALAN_NEDEN { get; set; } //(char(1), null)
        public string EKALAN { get; set; } //(varchar(200), null)
        public string EKALAN1 { get; set; } //(varchar(100), null)
        public decimal REDMIK { get; set; } //(decimal(15,5), null)
        public byte REDNEDEN { get; set; } //(tinyint, null)
        public string AMBAR_KABULNO { get; set; } //(varchar(15), null)
        public byte FIRMA_DOVTIP { get; set; } //(tinyint, null)
        public decimal FIRMA_DOVTUT { get; set; } //(decimal(28,8), null)
        public decimal FIRMA_DOVMAL { get; set; } //(decimal(28,8), null)
        public string UPDATE_KODU { get; set; } //(char(1), null)
        public string IRSALIYE_NO { get; set; } //(varchar(15), null)
        public DateTime IRSALIYE_TARIH { get; set; } //(datetime, null)
        public string KOSULKODU { get; set; } //(varchar(8), null)
        public byte ECZA_FAT_TIP { get; set; } //(tinyint, null)
        public DateTime STHAR_TESTAR { get; set; } //(datetime, null)
        public byte OLCUBR { get; set; } //(tinyint, null)
        public int INCKEYNO { get; set; } //(int, not null)
        public DateTime VADE_TARIHI { get; set; } //(datetime, null)
        public string LISTE_NO { get; set; } //(varchar(8), null)
        public int BAGLANTI_NO { get; set; } //(int, null)
        public string MUH_KODU { get; set; } //(varchar(35), null)
        public string S_YEDEK1 { get; set; } //(varchar(15), null)
        public string S_YEDEK2 { get; set; } //(varchar(8), null)
        public decimal F_YEDEK3 { get; set; } //(decimal(28,8), null)
        public decimal F_YEDEK4 { get; set; } //(decimal(28,8), null)
        public decimal F_YEDEK5 { get; set; } //(decimal(28,8), null)
        public string C_YEDEK6 { get; set; } //(char(1), null)
        public byte B_YEDEK7 { get; set; } //(tinyint, null)
        public int L_YEDEK9 { get; set; } //(int, null)
        public DateTime D_YEDEK10 { get; set; } //(datetime, null)
        public string PROJE_KODU { get; set; } //(varchar(15), null)
        public DateTime FIYATTARIHI { get; set; } //(datetime, null)
        public DateTime KOSULTARIHI { get; set; } //(datetime, null)
        public byte EXPORTTYPE { get; set; } //(tinyint, null)
        public decimal EXPORTMIK { get; set; } //(decimal(28,8), null)
        public string ONAYTIPI { get; set; } //(char(1), not null)
        public int ONAYNUM { get; set; } //(int, not null)
        public decimal KKMALF { get; set; } //(decimal(28,8), null)
        public string YAPKOD { get; set; } //(varchar(15), null)
        public string MAMYAPKOD { get; set; } //(varchar(15), null)
        public decimal OTVFIYAT { get; set; } //(decimal(28,8), null)
        public string CARI_KODU { get; set; } //(varchar(15), null)
        public string CARI_ISIM { get; set; } //(varchar(100), null)
        public DateTime SIPARIS_TEST { get; set; } //(datetime, null)
        public decimal GENELTOPLAM { get; set; } //(decimal(28,8), null)
        public decimal KALAN { get; set; } //(decimal(29,8), null)
    }



}
