namespace NetSatis.Entities.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Tumsqlviews : DbMigration
    {
        public override void Up()
        {
            #region BSD_VW_CEKSEN_SONISLEM
            Sql(@"Create   VIEW [dbo].[BSD_VW_CEKSEN_SONISLEM]
AS
SELECT        NEWID() AS ID, C.SC_NO, C.VADETRH, C.SC_GIRTRH, C.SC_CIKTRH, C.SC_VERILENK AS VERILEN_CARI, Replace(Replace(replace(CR.CARI_ISIM, 'Ý', 'I'), 'Þ', 'S'), 'Ð', 'G') AS VERILEN_CARI_ISIM, 
                         C.SC_VERENK AS VEREN_CARI, Replace(Replace(REPLACE(CR2.CARI_ISIM, 'Þ', 'S'), 'Ý', 'I'), 'Ð', 'G') AS VEREN_CARI_ISIM, CASE WHEN C.DOVTIP = 0 THEN C.TUTAR ELSE C.DOVTUT END AS TUTAR, 
                         ISNULL(KUR.ISIM, 'TL') AS KURISIM, C.SUBE_KODU, C.YERI AS BANKA_YER, 
                         CASE WHEN C.SC_SONDUR = 'B' THEN 'Bizde' WHEN C.SC_SONDUR = 'P' THEN 'Protestolu' WHEN C.SC_SONDUR = 'I' THEN 'İade'  WHEN C.SC_SONDUR = 'O' THEN 'Ödendi' END AS DURUM, 
                         CASE WHEN C.SC_YERI = 'C' THEN 'Ciro' WHEN C.SC_YERI = 'P' THEN 'Portföy' WHEN C.SC_YERI = 'T' THEN 'Tahsil' WHEN C.SC_YERI = 'I' THEN 'İade' WHEN C.SC_YERI = 'E' THEN 'Teminat' END AS YERI, 
                         'Bizim Senetimiz' AS TIPI, C.PLASIYER_KODU, CASE WHEN C.SC_GIRTRH > ISNULL(C.SC_CIKTRH, '19000101') THEN C.SC_GIRTRH ELSE C.SC_CIKTRH END TARIH
FROM            TBLBSEN C LEFT OUTER JOIN
                         TBLCASABIT CR ON CR.CARI_KOD = C.SC_VERILENK LEFT OUTER JOIN
                         TBLCASABIT CR2 ON CR2.CARI_KOD = C.SC_VERENK LEFT OUTER JOIN
                         NETSIS..KUR AS KUR ON KUR.SIRA = C.DOVTIP
UNION
SELECT        NEWID() AS ID, C.SC_NO, C.VADETRH, C.SC_GIRTRH, C.SC_CIKTRH, C.SC_VERILENK AS VERILEN_CARI, Replace(Replace(replace(CR.CARI_ISIM, 'Ý', 'I'), 'Þ', 'S'), 'Ð', 'G') AS VERILEN_CARI_ISIM, 
                         C.SC_VERENK AS VEREN_CARI, Replace(Replace(REPLACE(CR2.CARI_ISIM, 'Þ', 'S'), 'Ý', 'I'), 'Ð', 'G') AS VEREN_CARI_ISIM, CASE WHEN C.DOVTIP = 0 THEN C.TUTAR ELSE C.DOVTUT END AS TUTAR, 
                         ISNULL(KUR.ISIM, 'TL') AS KURISIM, C.SUBE_KODU, C.YERI AS BANKA_YER, 
                         CASE WHEN C.SC_SONDUR = 'B' THEN 'Bizde' WHEN C.SC_SONDUR = 'P' THEN 'Protestolu' WHEN C.SC_SONDUR = 'I' THEN 'İade'  WHEN C.SC_SONDUR = 'O' THEN 'Ödendi' END AS DURUM, 
                         CASE WHEN C.SC_YERI = 'C' THEN 'Ciro' WHEN C.SC_YERI = 'P' THEN 'Portföy' WHEN C.SC_YERI = 'T' THEN 'Tahsil' WHEN C.SC_YERI = 'I' THEN 'İade' WHEN C.SC_YERI = 'E' THEN 'Teminat' END AS YERI, 
                         'Müşteri Seneti' AS TIPI, C.PLASIYER_KODU, CASE WHEN C.SC_GIRTRH > ISNULL(C.SC_CIKTRH, '19000101') THEN C.SC_GIRTRH ELSE C.SC_CIKTRH END TARIH
FROM            TBLMSEN C LEFT OUTER JOIN
                         TBLCASABIT CR ON CR.CARI_KOD = C.SC_VERILENK LEFT OUTER JOIN
                         TBLCASABIT CR2 ON CR2.CARI_KOD = C.SC_VERENK LEFT OUTER JOIN
                         NETSIS..KUR AS KUR ON KUR.SIRA = C.DOVTIP
UNION
SELECT        NEWID() AS ID, C.SC_NO, C.VADETRH, C.SC_GIRTRH, C.SC_CIKTRH, C.SC_VERILENK AS VERILEN_CARI, Replace(Replace(replace(CR.CARI_ISIM, 'Ý', 'I'), 'Þ', 'S'), 'Ð', 'G') AS VERILEN_CARI_ISIM, 
                         C.SC_VERENK AS VEREN_CARI, Replace(Replace(REPLACE(CR2.CARI_ISIM, 'Þ', 'S'), 'Ý', 'I'), 'Ð', 'G') AS VEREN_CARI_ISIM, CASE WHEN C.DOVTIP = 0 THEN C.TUTAR ELSE C.DOVTUT END AS TUTAR, 
                         ISNULL(KUR.ISIM, 'TL') AS KURISIM, C.SUBE_KODU, C.YERI AS BANKA_YER, 
                         CASE WHEN C.SC_SONDUR = 'B' THEN 'Bizde' WHEN C.SC_SONDUR = 'P' THEN 'Protestolu'  WHEN C.SC_SONDUR = 'I' THEN 'İade' WHEN C.SC_SONDUR = 'O' THEN 'Ödendi' END AS DURUM, 
                         CASE WHEN C.SC_YERI = 'C' THEN 'Ciro' WHEN C.SC_YERI = 'P' THEN 'Portföy' WHEN C.SC_YERI = 'T' THEN 'Tahsil' WHEN C.SC_YERI = 'I' THEN 'İade' WHEN C.SC_YERI = 'E' THEN 'Teminat' END AS YERI, 
                         'Müşteri Çeki' AS TIPI, C.PLASIYER_KODU, CASE WHEN C.SC_GIRTRH > ISNULL(C.SC_CIKTRH, '19000101') THEN C.SC_GIRTRH ELSE C.SC_CIKTRH END TARIH
FROM            TBLMCEK C LEFT OUTER JOIN
                         TBLCASABIT CR ON CR.CARI_KOD = C.SC_VERILENK LEFT OUTER JOIN
                         TBLCASABIT CR2 ON CR2.CARI_KOD = C.SC_VERENK LEFT OUTER JOIN
                         NETSIS..KUR AS KUR ON KUR.SIRA = C.DOVTIP
UNION
SELECT        NEWID() AS ID, C.SC_NO, C.VADETRH, C.SC_GIRTRH, C.SC_CIKTRH, C.SC_VERILENK AS VERILEN_CARI, Replace(Replace(replace(CR.CARI_ISIM, 'Ý', 'I'), 'Þ', 'S'), 'Ð', 'G') AS VERILEN_CARI_ISIM, 
                         C.SC_VERENK AS VEREN_CARI, Replace(Replace(REPLACE(CR2.CARI_ISIM, 'Þ', 'S'), 'Ý', 'I'), 'Ð', 'G') AS VEREN_CARI_ISIM, CASE WHEN C.DOVTIP = 0 THEN C.TUTAR ELSE C.DOVTUT END AS TUTAR, 
                         ISNULL(KUR.ISIM, 'TL') AS KURISIM, C.SUBE_KODU, C.YERI AS BANKA_YER, 
                         CASE WHEN C.SC_SONDUR = 'B' THEN 'Bizde' WHEN C.SC_SONDUR = 'P' THEN 'Protestolu'  WHEN C.SC_SONDUR = 'I' THEN 'İade'  WHEN C.SC_SONDUR = 'O' THEN 'Ödendi' END AS DURUM, 
                         CASE WHEN C.SC_YERI = 'C' THEN 'Ciro' WHEN C.SC_YERI = 'P' THEN 'Portföy' WHEN C.SC_YERI = 'T' THEN 'Tahsil' WHEN C.SC_YERI = 'I' THEN 'İade' WHEN C.SC_YERI = 'E' THEN 'Teminat' END AS YERI, 
                         'Bizim Çekimiz' AS TIPI, C.PLASIYER_KODU, CASE WHEN ISNULL(C.SC_GIRTRH, '19000101') > ISNULL(C.SC_CIKTRH, '19000101') THEN C.SC_GIRTRH ELSE C.SC_CIKTRH END TARIH
FROM            TBLBCEK C LEFT OUTER JOIN
                         TBLCASABIT CR ON CR.CARI_KOD = C.SC_VERILENK LEFT OUTER JOIN
                         TBLCASABIT CR2 ON CR2.CARI_KOD = C.SC_VERENK LEFT OUTER JOIN
                         NETSIS..KUR AS KUR ON KUR.SIRA = C.DOVTIP");
            #endregion

            #region ZZ_BSD_VW_DEPOBAKIYE
              Sql(@"CREATE VIEW [dbo].[ZZ_BSD_VW_DEPOBAKIYE]
AS
SELECT        dbo.TBLSTSABIT.STOK_KODU, dbo.TBLSTSABIT.STOK_ADI, SUM(ISNULL(CASE WHEN STOKANA.DEPO_KODU = '1' THEN ISNULL(dbo.STOKANA.BAKIYE, 0) END, 0)) AS HAMMADDDE, 
                         SUM(ISNULL(CASE WHEN STOKANA.DEPO_KODU = '2' THEN ISNULL(dbo.STOKANA.BAKIYE, 0) END, 0)) AS URETIM, SUM(ISNULL(CASE WHEN STOKANA.DEPO_KODU = '3' THEN ISNULL(dbo.STOKANA.BAKIYE, 0) END, 0)) 
                         AS MAMÜL, SUM(ISNULL(CASE WHEN STOKANA.DEPO_KODU = '4' THEN ISNULL(dbo.STOKANA.BAKIYE, 0) END, 0)) AS ATIL, SUM(ISNULL(CASE WHEN STOKANA.DEPO_KODU = '5' THEN ISNULL(dbo.STOKANA.BAKIYE, 0) END,
                          0)) AS GALVANIZ, SUM(ISNULL(CASE WHEN STOKANA.DEPO_KODU = '0' THEN ISNULL(dbo.STOKANA.BAKIYE, 0) END, 0)) AS DIGER
FROM            dbo.TBLSTOKDP INNER JOIN
                         dbo.STOKANA ON dbo.TBLSTOKDP.DEPO_KODU = dbo.STOKANA.DEPO_KODU RIGHT OUTER JOIN
                         dbo.TBLSTSABIT ON dbo.STOKANA.STOK_KODU = dbo.TBLSTSABIT.STOK_KODU
GROUP BY dbo.TBLSTSABIT.STOK_KODU, dbo.TBLSTSABIT.STOK_ADI");
            #endregion

            #region ZZ_BSD_VW_SIPARIS
              Sql(@"CREATE VIEW [dbo].[ZZ_BSD_VW_SIPARIS]
AS
SELECT        dbo.SIPATRA.STOK_KODU, dbo.SIPATRA.FISNO, dbo.SIPATRA.STHAR_GCMIK, dbo.SIPATRA.STHAR_GCMIK2, dbo.SIPATRA.CEVRIM, dbo.SIPATRA.STHAR_GCKOD, dbo.SIPATRA.STHAR_TARIH, dbo.SIPATRA.STHAR_NF, 
                         dbo.SIPATRA.STHAR_BF, dbo.SIPATRA.STHAR_IAF, dbo.SIPATRA.STHAR_KDV, dbo.SIPATRA.DEPO_KODU, dbo.SIPATRA.STHAR_ACIKLAMA, dbo.SIPATRA.STHAR_SATISK, dbo.SIPATRA.STHAR_MALFISK, 
                         dbo.SIPATRA.STHAR_FTIRSIP, dbo.SIPATRA.STHAR_SATISK2, dbo.SIPATRA.LISTE_FIAT, dbo.SIPATRA.STHAR_HTUR, dbo.SIPATRA.STHAR_DOVTIP, dbo.SIPATRA.PROMASYON_KODU, dbo.SIPATRA.STHAR_DOVFIAT, 
                         dbo.SIPATRA.STHAR_ODEGUN, dbo.SIPATRA.STRA_SATISK3, dbo.SIPATRA.STRA_SATISK4, dbo.SIPATRA.STRA_SATISK5, dbo.SIPATRA.STRA_SATISK6, dbo.SIPATRA.STHAR_BGTIP, dbo.SIPATRA.STHAR_KOD1, 
                         dbo.SIPATRA.STHAR_KOD2, dbo.SIPATRA.STHAR_SIPNUM, dbo.SIPATRA.STHAR_CARIKOD, dbo.SIPATRA.STHAR_SIP_TURU, dbo.SIPATRA.PLASIYER_KODU, dbo.SIPATRA.EKALAN_NEDEN, dbo.SIPATRA.EKALAN, 
                         dbo.SIPATRA.EKALAN1, dbo.SIPATRA.REDMIK, dbo.SIPATRA.REDNEDEN, dbo.SIPATRA.SIRA, dbo.SIPATRA.STRA_SIPKONT, dbo.SIPATRA.AMBAR_KABULNO, dbo.SIPATRA.FIRMA_DOVTIP, dbo.SIPATRA.FIRMA_DOVTUT, 
                         dbo.SIPATRA.FIRMA_DOVMAL, dbo.SIPATRA.UPDATE_KODU, dbo.SIPATRA.IRSALIYE_NO, dbo.SIPATRA.IRSALIYE_TARIH, dbo.SIPATRA.KOSULKODU, dbo.SIPATRA.ECZA_FAT_TIP, dbo.SIPATRA.STHAR_TESTAR, 
                         dbo.SIPATRA.OLCUBR, dbo.SIPATRA.INCKEYNO, dbo.SIPATRA.VADE_TARIHI, dbo.SIPATRA.LISTE_NO, dbo.SIPATRA.BAGLANTI_NO, dbo.SIPATRA.SUBE_KODU, dbo.SIPATRA.MUH_KODU, dbo.SIPATRA.S_YEDEK1, 
                         dbo.SIPATRA.S_YEDEK2, dbo.SIPATRA.F_YEDEK3, dbo.SIPATRA.F_YEDEK4, dbo.SIPATRA.F_YEDEK5, dbo.SIPATRA.C_YEDEK6, dbo.SIPATRA.B_YEDEK7, dbo.SIPATRA.I_YEDEK8, dbo.SIPATRA.L_YEDEK9, 
                         dbo.SIPATRA.D_YEDEK10, dbo.SIPATRA.PROJE_KODU, dbo.SIPATRA.FIYATTARIHI, dbo.SIPATRA.KOSULTARIHI, dbo.SIPATRA.SATISK1TIP, dbo.SIPATRA.SATISK2TIP, dbo.SIPATRA.SATISK3TIP, dbo.SIPATRA.SATISK4TIP, 
                         dbo.SIPATRA.SATISK5TIP, dbo.SIPATRA.SATISK6TIP, dbo.SIPATRA.EXPORTTYPE, dbo.SIPATRA.EXPORTMIK, dbo.SIPATRA.ONAYTIPI, dbo.SIPATRA.ONAYNUM, dbo.SIPATRA.KKMALF, dbo.SIPATRA.STRA_IRSKONT, 
                         dbo.SIPATRA.YAPKOD, dbo.SIPATRA.MAMYAPKOD, dbo.SIPATRA.OTVFIYAT, dbo.SIPANA.CARI_KODU, dbo.SIPANA.CARI_ISIM, dbo.SIPANA.SIPARIS_TEST, dbo.SIPANA.GENELTOPLAM, 
                         dbo.SIPATRA.STHAR_GCMIK - dbo.SIPATRA.FIRMA_DOVTUT AS KALAN
FROM            dbo.SIPATRA LEFT OUTER JOIN
                         dbo.SIPANA ON dbo.SIPATRA.FISNO = dbo.SIPANA.FATIRS_NO
WHERE        (dbo.SIPATRA.STHAR_GCKOD = 'G') AND (dbo.SIPATRA.STHAR_BGTIP = 'I') AND (dbo.SIPATRA.STHAR_GCMIK - dbo.SIPATRA.FIRMA_DOVTUT > 0) AND (dbo.SIPATRA.STHAR_HTUR = 'H')
");
            #endregion

            #region ZZZ_CARI_RAPORU
              Sql(@"Create   VIEW [dbo].[ZZZ_CARI_RAPORU] 
AS
	SELECT C.CARI_KOD,REPLACE(REPLACE(REPLACE(SUBSTRING(C.CARI_ISIM, 1, 40), 'Þ', 'Ş'), 'Ý', 'İ'), 'Ð', 'Ğ') AS CARI_ISIM ,C.CARI_TIP, C.GRUP_KODU, C.ISLETME_KODU, C.SUBE_KODU, C.CARI_TEL,
	(SELECT (ISNULL(SUM(BORC),0)- ISNULL(SUM(ALACAK),0)) FROM TBLCAHAR WHERE DOVIZ_TURU=0 AND CARI_KOD = C.CARI_KOD ) AS BAKIYE_TL,

	((ISNULL((SELECT SUM(DOVIZ_TUTAR) FROM TBLCAHAR WHERE CARI_KOD = C.CARI_KOD AND DOVIZ_TURU =(SELECT SIRA FROM NETSIS..KUR WHERE NETSISSIRA=1) AND ALACAK=0),0) - 
	(ISNULL((SELECT SUM(DOVIZ_TUTAR) FROM TBLCAHAR WHERE CARI_KOD = C.CARI_KOD AND DOVIZ_TURU =(SELECT SIRA FROM NETSIS..KUR WHERE NETSISSIRA=1) AND BORC=0),0)))) AS BAKIYE_USD,

	((ISNULL((SELECT SUM(DOVIZ_TUTAR) FROM TBLCAHAR WHERE CARI_KOD = C.CARI_KOD AND DOVIZ_TURU =(SELECT SIRA FROM NETSIS..KUR WHERE NETSISSIRA=20) AND ALACAK=0),0) - 
	(ISNULL((SELECT SUM(DOVIZ_TUTAR) FROM TBLCAHAR WHERE CARI_KOD = C.CARI_KOD AND DOVIZ_TURU =(SELECT SIRA FROM NETSIS..KUR WHERE NETSISSIRA=20) AND BORC=0),0)))) AS BAKIYE_EUR,

	(SELECT (ISNULL(SUM(BORC),0)- ISNULL(SUM(ALACAK),0)) FROM TBLCAHAR WHERE DOVIZ_TURU IN(SELECT SIRA FROM NETSIS..KUR WHERE NETSISSIRA<>1 AND NETSISSIRA<>20 AND ISNULL(NETSISSIRA,0)<>0) AND CARI_KOD = C.CARI_KOD ) AS BAKIYE_DIGER,

	(SELECT ISNULL(SUM((TBLSIPATRA.STHAR_GCMIK-TBLSIPATRA.FIRMA_DOVTUT)* TBLSIPATRA.STHAR_NF),0) FROM TBLSIPATRA WHERE STHAR_ACIKLAMA=C.CARI_KOD AND STHAR_DOVTIP=0 AND STHAR_FTIRSIP='6' AND STHAR_HTUR <>'K' AND (STHAR_GCMIK-FIRMA_DOVTUT)>0)-
	(SELECT ISNULL(SUM((TBLSIPATRA.STHAR_GCMIK-TBLSIPATRA.FIRMA_DOVTUT)* TBLSIPATRA.STHAR_NF),0) FROM TBLSIPATRA WHERE STHAR_ACIKLAMA=C.CARI_KOD AND STHAR_DOVTIP=0 AND STHAR_FTIRSIP='7' AND STHAR_HTUR <>'K' AND (STHAR_GCMIK-FIRMA_DOVTUT)>0) AS SIPARIS_TL,

	(SELECT ISNULL(SUM((STHAR_GCMIK-FIRMA_DOVTUT)*STHAR_DOVFIAT*(1-TBLSIPAMAS.GEN_ISK1O/100)*(1-TBLSIPAMAS.GEN_ISK2O/100)*(1-TBLSIPAMAS.GEN_ISK3O/100)* 
	(1-(CASE WHEN TBLSIPATRA.STHAR_SATISK <= 0.001 THEN (TBLSIPATRA.STHAR_SATISK * 100000) ELSE TBLSIPATRA.STHAR_SATISK END )/100) * (1-TBLSIPATRA.STHAR_SATISK2/100) * (1-TBLSIPATRA.STRA_SATISK3/100) * (1-TBLSIPATRA.STRA_SATISK4/100) * (1-TBLSIPATRA.STRA_SATISK5/100) * (1-TBLSIPATRA.STRA_SATISK6/100) ),0) FROM TBLSIPATRA 
	INNER JOIN TBLSIPAMAS ON TBLSIPATRA.FISNO=TBLSIPAMAS.FATIRS_NO AND TBLSIPATRA.STHAR_FTIRSIP=TBLSIPAMAS.FTIRSIP
	WHERE STHAR_ACIKLAMA=C.CARI_KOD AND STHAR_DOVTIP=(SELECT SIRA FROM NETSIS..KUR WHERE NETSISSIRA=1) AND STHAR_FTIRSIP='6' AND STHAR_HTUR <>'K'  AND (STHAR_GCMIK-FIRMA_DOVTUT)>0)-
	(SELECT ISNULL(SUM((STHAR_GCMIK-FIRMA_DOVTUT)*STHAR_DOVFIAT*(1-TBLSIPAMAS.GEN_ISK1O/100)*(1-TBLSIPAMAS.GEN_ISK2O/100)*(1-TBLSIPAMAS.GEN_ISK3O/100)* 
	(1-(CASE WHEN TBLSIPATRA.STHAR_SATISK <= 0.001 THEN (TBLSIPATRA.STHAR_SATISK * 100000) ELSE TBLSIPATRA.STHAR_SATISK END )/100) * (1-TBLSIPATRA.STHAR_SATISK2/100) * (1-TBLSIPATRA.STRA_SATISK3/100) * (1-TBLSIPATRA.STRA_SATISK4/100) * (1-TBLSIPATRA.STRA_SATISK5/100) * (1-TBLSIPATRA.STRA_SATISK6/100) ),0) FROM TBLSIPATRA 
	INNER JOIN TBLSIPAMAS ON TBLSIPATRA.FISNO=TBLSIPAMAS.FATIRS_NO AND TBLSIPATRA.STHAR_FTIRSIP=TBLSIPAMAS.FTIRSIP
	WHERE STHAR_ACIKLAMA=C.CARI_KOD AND STHAR_DOVTIP=(SELECT SIRA FROM NETSIS..KUR WHERE NETSISSIRA=1) AND STHAR_FTIRSIP='7' AND STHAR_HTUR <>'K' AND (STHAR_GCMIK-FIRMA_DOVTUT)>0) AS SIPARIS_USD,

	(SELECT ISNULL(SUM((STHAR_GCMIK-FIRMA_DOVTUT)*STHAR_DOVFIAT*(1-TBLSIPAMAS.GEN_ISK1O/100)*(1-TBLSIPAMAS.GEN_ISK2O/100)*(1-TBLSIPAMAS.GEN_ISK3O/100)* 
	(1-(CASE WHEN TBLSIPATRA.STHAR_SATISK <= 0.001 THEN (TBLSIPATRA.STHAR_SATISK * 100000) ELSE TBLSIPATRA.STHAR_SATISK END )/100) * (1-TBLSIPATRA.STHAR_SATISK2/100) * (1-TBLSIPATRA.STRA_SATISK3/100) * (1-TBLSIPATRA.STRA_SATISK4/100) * (1-TBLSIPATRA.STRA_SATISK5/100) * (1-TBLSIPATRA.STRA_SATISK6/100) ),0) FROM TBLSIPATRA 
	INNER JOIN TBLSIPAMAS ON TBLSIPATRA.FISNO=TBLSIPAMAS.FATIRS_NO AND TBLSIPATRA.STHAR_FTIRSIP=TBLSIPAMAS.FTIRSIP
	WHERE STHAR_ACIKLAMA=C.CARI_KOD AND STHAR_DOVTIP=(SELECT SIRA FROM NETSIS..KUR WHERE NETSISSIRA=20) AND STHAR_FTIRSIP='6' AND STHAR_HTUR <>'K' AND (STHAR_GCMIK-FIRMA_DOVTUT)>0)-
	(SELECT ISNULL(SUM((STHAR_GCMIK-FIRMA_DOVTUT)*STHAR_DOVFIAT*(1-TBLSIPAMAS.GEN_ISK1O/100)*(1-TBLSIPAMAS.GEN_ISK2O/100)*(1-TBLSIPAMAS.GEN_ISK3O/100)* 
	(1-(CASE WHEN TBLSIPATRA.STHAR_SATISK <= 0.001 THEN (TBLSIPATRA.STHAR_SATISK * 100000) ELSE TBLSIPATRA.STHAR_SATISK END )/100) * (1-TBLSIPATRA.STHAR_SATISK2/100) * (1-TBLSIPATRA.STRA_SATISK3/100) * (1-TBLSIPATRA.STRA_SATISK4/100) * (1-TBLSIPATRA.STRA_SATISK5/100) * (1-TBLSIPATRA.STRA_SATISK6/100) ),0) FROM TBLSIPATRA 
	INNER JOIN TBLSIPAMAS ON TBLSIPATRA.FISNO=TBLSIPAMAS.FATIRS_NO AND TBLSIPATRA.STHAR_FTIRSIP=TBLSIPAMAS.FTIRSIP
	WHERE STHAR_ACIKLAMA=C.CARI_KOD AND STHAR_DOVTIP=(SELECT SIRA FROM NETSIS..KUR WHERE NETSISSIRA=20) AND STHAR_FTIRSIP='7' AND STHAR_HTUR <>'K' AND (STHAR_GCMIK-FIRMA_DOVTUT)>0) AS SIPARIS_EUR,

	(SELECT ISNULL(SUM((TBLSIPATRA.STHAR_GCMIK-TBLSIPATRA.FIRMA_DOVTUT)* TBLSIPATRA.STHAR_NF),0) FROM TBLSIPATRA WHERE STHAR_ACIKLAMA=C.CARI_KOD AND (STHAR_DOVTIP NOT IN(SELECT SIRA FROM NETSIS..KUR WHERE (NETSISSIRA=20 OR NETSISSIRA=1) ) AND STHAR_DOVTIP<>0) AND STHAR_FTIRSIP='6' AND STHAR_HTUR <>'K' AND (STHAR_GCMIK-FIRMA_DOVTUT)>0)-
	(SELECT ISNULL(SUM((TBLSIPATRA.STHAR_GCMIK-TBLSIPATRA.FIRMA_DOVTUT)* TBLSIPATRA.STHAR_NF),0) FROM TBLSIPATRA WHERE STHAR_ACIKLAMA=C.CARI_KOD AND (STHAR_DOVTIP NOT IN(SELECT SIRA FROM NETSIS..KUR WHERE (NETSISSIRA=20 OR NETSISSIRA=1) ) AND STHAR_DOVTIP<>0) AND STHAR_FTIRSIP='7' AND STHAR_HTUR <>'K' AND (STHAR_GCMIK-FIRMA_DOVTUT)>0) AS SIPARIS_DIGER


	FROM TBLCASABIT C
	WHERE C.ISLETME_KODU <> -2
	GROUP BY C.CARI_KOD, C.CARI_TIP, C.CARI_ISIM, C.GRUP_KODU, C.ISLETME_KODU, C.SUBE_KODU, C.CARI_TEL");
            #endregion

            #region ZZ_VW_SATICI_SIP
              Sql(@"CREATE VIEW [dbo].[ZZ_BSD_VW_SATICI_SIP]
AS
SELECT        dbo.ZZ_BSD_VW_DEPOBAKIYE.STOK_KODU, dbo.ZZ_BSD_VW_DEPOBAKIYE.STOK_ADI, dbo.ZZ_BSD_VW_DEPOBAKIYE.HAMMADDDE, dbo.ZZ_BSD_VW_DEPOBAKIYE.URETIM, 
                         dbo.ZZ_BSD_VW_DEPOBAKIYE.MAMÜL, dbo.ZZ_BSD_VW_DEPOBAKIYE.ATIL, dbo.ZZ_BSD_VW_DEPOBAKIYE.DIGER, dbo.ZZ_BSD_VW_DEPOBAKIYE.GALVANIZ, 
                         SUM(ISNULL(dbo.ZZ_BSD_VW_SIPARIS.STHAR_GCMIK, 0)) AS SIP_MIKTARI, SUM(ISNULL(dbo.ZZ_BSD_VW_SIPARIS.FIRMA_DOVTUT, 0)) AS TESLIM_EDILEN_MIK, 
                         SUM(ISNULL(dbo.ZZ_BSD_VW_SIPARIS.KALAN, 0)) AS KALAN, AVG(ISNULL(dbo.ZZ_BSD_VW_SIPARIS.STHAR_NF, 0)) AS SIP_FIYATI, AVG(ISNULL(dbo.TBLSTHAR.STHAR_NF, 0)) AS IRS_FIYATI, 
                         AVG(ISNULL(dbo.TBLSTHAR.STHAR_DOVFIAT, 0)) AS DOV_FIYAT, ISNULL(dbo.TBLSTSABIT.DOV_ALIS_FIAT, 0) AS DOV_ALIS_FIAT, dbo.ZZZ_CARI_RAPORU.CARI_ISIM, dbo.ZZZ_CARI_RAPORU.BAKIYE_TL, 
                         dbo.ZZZ_CARI_RAPORU.BAKIYE_USD, dbo.ZZZ_CARI_RAPORU.BAKIYE_EUR, dbo.ZZZ_CARI_RAPORU.SIPARIS_TL, dbo.ZZZ_CARI_RAPORU.SIPARIS_USD, dbo.ZZZ_CARI_RAPORU.SIPARIS_EUR, 
                         dbo.ZZ_BSD_VW_SIPARIS.STHAR_HTUR, dbo.TBLSTSABITEK.KULL1N
FROM            dbo.TBLSTSABITEK RIGHT OUTER JOIN
                         dbo.ZZ_BSD_VW_SIPARIS ON dbo.TBLSTSABITEK.STOK_KODU = dbo.ZZ_BSD_VW_SIPARIS.STOK_KODU LEFT OUTER JOIN
                         dbo.ZZZ_CARI_RAPORU ON dbo.ZZ_BSD_VW_SIPARIS.STHAR_ACIKLAMA = dbo.ZZZ_CARI_RAPORU.CARI_KOD RIGHT OUTER JOIN
                         dbo.TBLSTSABIT ON dbo.ZZ_BSD_VW_SIPARIS.STOK_KODU = dbo.TBLSTSABIT.STOK_KODU LEFT OUTER JOIN
                         dbo.TBLSTHAR ON dbo.ZZ_BSD_VW_SIPARIS.STOK_KODU = dbo.TBLSTHAR.STOK_KODU AND dbo.ZZ_BSD_VW_SIPARIS.FISNO = dbo.TBLSTHAR.STHAR_SIPNUM RIGHT OUTER JOIN
                         dbo.ZZ_BSD_VW_DEPOBAKIYE ON dbo.ZZ_BSD_VW_SIPARIS.STOK_KODU = dbo.ZZ_BSD_VW_DEPOBAKIYE.STOK_KODU
GROUP BY dbo.ZZ_BSD_VW_DEPOBAKIYE.STOK_KODU, dbo.ZZ_BSD_VW_DEPOBAKIYE.STOK_ADI, dbo.ZZ_BSD_VW_DEPOBAKIYE.HAMMADDDE, dbo.ZZ_BSD_VW_DEPOBAKIYE.URETIM, 
                         dbo.ZZ_BSD_VW_DEPOBAKIYE.MAMÜL, dbo.ZZ_BSD_VW_DEPOBAKIYE.ATIL, dbo.ZZ_BSD_VW_DEPOBAKIYE.DIGER, dbo.ZZ_BSD_VW_DEPOBAKIYE.GALVANIZ, ISNULL(dbo.TBLSTSABIT.DOV_ALIS_FIAT, 0), 
                         dbo.ZZZ_CARI_RAPORU.CARI_ISIM, dbo.ZZZ_CARI_RAPORU.BAKIYE_TL, dbo.ZZZ_CARI_RAPORU.BAKIYE_USD, dbo.ZZZ_CARI_RAPORU.BAKIYE_EUR, dbo.ZZZ_CARI_RAPORU.SIPARIS_TL, 
                         dbo.ZZZ_CARI_RAPORU.SIPARIS_USD, dbo.ZZZ_CARI_RAPORU.SIPARIS_EUR, dbo.ZZ_BSD_VW_SIPARIS.STHAR_HTUR, dbo.TBLSTSABITEK.KULL1N
");
            #endregion

            #region BSD_RAPOR_DEPO_SIPARIS_DURUM
              Sql(@"CREATE PROC [dbo].[BSD_RAPOR_DEPO_SIPARIS_DURUM]

AS

BEGIN
exec nsp_netsesguncelle 2, 'ys0001',1,0,'e','h','2',-1,'H',0,0,'H'
     select * from ZZ_BSD_VW_SATICI_SIP

END");
            #endregion

            #region BSD_TEKLIF_STOK
               Sql(@"CREATE VIEW [dbo].[BSD_TEKLIF_STOK]
AS
SELECT        dbo.TBLTEKLIFTRA.STOK_KODU, dbo.TBLTEKLIFTRA.FISNO, dbo.TBLTEKLIFTRA.STHAR_GCMIK, dbo.TBLTEKLIFTRA.STHAR_GCMIK2, dbo.TBLTEKLIFTRA.CEVRIM, dbo.TBLTEKLIFTRA.STHAR_GCKOD, 
                         dbo.TBLTEKLIFTRA.STHAR_TARIH, dbo.TBLTEKLIFTRA.STHAR_NF, dbo.TBLTEKLIFTRA.STHAR_BF, dbo.TBLTEKLIFTRA.STHAR_IAF, dbo.TBLTEKLIFTRA.STHAR_KDV, dbo.TBLTEKLIFTRA.DEPO_KODU, 
                         dbo.TBLTEKLIFTRA.STHAR_ACIKLAMA, dbo.TBLTEKLIFTRA.STHAR_SATISK, dbo.TBLTEKLIFTRA.STHAR_MALFISK, dbo.TBLTEKLIFTRA.STHAR_FTIRSIP, dbo.TBLTEKLIFTRA.STHAR_SATISK2, 
                         dbo.TBLTEKLIFTRA.LISTE_FIAT, dbo.TBLTEKLIFTRA.STHAR_HTUR, dbo.TBLTEKLIFTRA.STHAR_DOVTIP, dbo.TBLTEKLIFTRA.PROMASYON_KODU, dbo.TBLTEKLIFTRA.STHAR_DOVFIAT, 
                         dbo.TBLTEKLIFTRA.STHAR_ODEGUN, dbo.TBLTEKLIFTRA.STRA_SATISK3, dbo.TBLTEKLIFTRA.STRA_SATISK4, dbo.TBLTEKLIFTRA.STRA_SATISK5, dbo.TBLTEKLIFTRA.STRA_SATISK6, 
                         dbo.TBLTEKLIFTRA.STHAR_BGTIP, dbo.TBLTEKLIFTRA.STHAR_KOD1, dbo.TBLTEKLIFTRA.STHAR_KOD2, dbo.TBLTEKLIFTRA.STHAR_SIPNUM, dbo.TBLTEKLIFTRA.STHAR_CARIKOD, 
                         dbo.TBLTEKLIFTRA.STHAR_SIP_TURU, dbo.TBLTEKLIFTRA.PLASIYER_KODU, dbo.TBLTEKLIFTRA.EKALAN_NEDEN, dbo.TBLTEKLIFTRA.EKALAN, dbo.TBLTEKLIFTRA.EKALAN1, dbo.TBLTEKLIFTRA.REDMIK, 
                         dbo.TBLTEKLIFTRA.REDNEDEN, dbo.TBLTEKLIFTRA.SIRA, dbo.TBLTEKLIFTRA.STRA_SIPKONT, dbo.TBLTEKLIFTRA.AMBAR_KABULNO, dbo.TBLTEKLIFTRA.FIRMA_DOVTIP, dbo.TBLTEKLIFTRA.FIRMA_DOVTUT, 
                         dbo.TBLTEKLIFTRA.FIRMA_DOVMAL, dbo.TBLTEKLIFTRA.UPDATE_KODU, dbo.TBLTEKLIFTRA.IRSALIYE_NO, dbo.TBLTEKLIFTRA.IRSALIYE_TARIH, dbo.TBLTEKLIFTRA.KOSULKODU, 
                         dbo.TBLTEKLIFTRA.ECZA_FAT_TIP, dbo.TBLTEKLIFTRA.STHAR_TESTAR, dbo.TBLTEKLIFTRA.OLCUBR, dbo.TBLTEKLIFTRA.INCKEYNO, dbo.TBLTEKLIFTRA.VADE_TARIHI, dbo.TBLTEKLIFTRA.LISTE_NO, 
                         dbo.TBLTEKLIFTRA.BAGLANTI_NO, dbo.TBLTEKLIFTRA.SUBE_KODU, dbo.TBLTEKLIFTRA.MUH_KODU, dbo.TBLTEKLIFTRA.S_YEDEK1, dbo.TBLTEKLIFTRA.S_YEDEK2, dbo.TBLTEKLIFTRA.F_YEDEK3, 
                         dbo.TBLTEKLIFTRA.F_YEDEK4, dbo.TBLTEKLIFTRA.F_YEDEK5, dbo.TBLTEKLIFTRA.C_YEDEK6, dbo.TBLTEKLIFTRA.B_YEDEK7, dbo.TBLTEKLIFTRA.I_YEDEK8, dbo.TBLTEKLIFTRA.L_YEDEK9, 
                         dbo.TBLTEKLIFTRA.D_YEDEK10, dbo.TBLTEKLIFTRA.PROJE_KODU, dbo.TBLTEKLIFTRA.FIYATTARIHI, dbo.TBLTEKLIFTRA.KOSULTARIHI, dbo.TBLTEKLIFTRA.SATISK1TIP, dbo.TBLTEKLIFTRA.SATISK2TIP, 
                         dbo.TBLTEKLIFTRA.SATISK3TIP, dbo.TBLTEKLIFTRA.SATISK4TIP, dbo.TBLTEKLIFTRA.SATISK5TIP, dbo.TBLTEKLIFTRA.SATISK6TIP, dbo.TBLTEKLIFTRA.EXPORTTYPE, dbo.TBLTEKLIFTRA.EXPORTMIK, 
                         dbo.TBLTEKLIFTRA.ONAYTIPI, dbo.TBLTEKLIFTRA.ONAYNUM, dbo.TBLTEKLIFTRA.KKMALF, dbo.TBLTEKLIFTRA.STRA_IRSKONT, dbo.TBLTEKLIFTRA.YAPKOD, dbo.TBLTEKLIFTRA.MAMYAPKOD, 
                         dbo.TBLTEKLIFTRA.OTVFIYAT, dbo.TBLTEKLIFTRA.IRS_INCKEYNO, dbo.TBLTEKLIFTRA.YEDEK11, dbo.TBLTEKLIFTRA.YEDEK12, dbo.TBLTEKLIFTRA.YEDEK13, dbo.TBLTEKLIFTRA.YEDEK14, 
                         dbo.TBLTEKLIFTRA.YEDEK15, dbo.TBLTEKLIFTRA.YEDEK16, dbo.TBLTEKLIFTRA.YEDEK17, dbo.TBLTEKLIFTRA.YEDEK18, dbo.TBLTEKLIFTRA.YEDEK19, dbo.TBLTEKLIFTRA.YEDEK20, 
                         dbo.TBLSTSABIT.STOK_ADI, dbo.TBLCASABIT.CARI_ISIM, dbo.TBLSTSABIT.GRUP_KODU
FROM            dbo.TBLSTSABIT RIGHT OUTER JOIN
                         dbo.TBLTEKLIFTRA LEFT OUTER JOIN
                         dbo.TBLCASABIT ON dbo.TBLTEKLIFTRA.STHAR_CARIKOD = dbo.TBLCASABIT.CARI_KOD ON dbo.TBLSTSABIT.STOK_KODU = dbo.TBLTEKLIFTRA.STOK_KODU
");
            #endregion

            #region BSD_SIPANA
              Sql(@"CREATE VIEW [dbo].[BSD_SIPANA]
AS
SELECT        dbo.TBLSIPAMAS.PLA_KODU AS PLASIYER_KODU, dbo.TBLSIPAMAS.SUBE_KODU, dbo.TBLSIPAMAS.FTIRSIP, dbo.TBLSIPAMAS.FATIRS_NO, dbo.TBLSIPAMAS.CARI_KODU, dbo.TBLSIPAMAS.TARIH, 
                         dbo.TBLSIPAMAS.TIPI, dbo.TBLSIPAMAS.BRUTTUTAR, dbo.TBLSIPAMAS.SAT_ISKT, dbo.TBLSIPAMAS.MFAZ_ISKT, dbo.TBLSIPAMAS.GEN_ISK1T, dbo.TBLSIPAMAS.GEN_ISK2T, dbo.TBLSIPAMAS.GEN_ISK3T, 
                         dbo.TBLSIPAMAS.GEN_ISK1O, dbo.TBLSIPAMAS.GEN_ISK2O, dbo.TBLSIPAMAS.GEN_ISK3O, dbo.TBLSIPAMAS.KDV, dbo.TBLSIPAMAS.FAT_ALTM1, dbo.TBLSIPAMAS.FAT_ALTM2, dbo.TBLSIPAMAS.ACIKLAMA, 
                         dbo.TBLSIPAMAS.KOD1, dbo.TBLSIPAMAS.KOD2, dbo.TBLSIPAMAS.ODEMEGUNU, dbo.TBLSIPAMAS.ODEMETARIHI, dbo.TBLSIPAMAS.KDV_DAHILMI, dbo.TBLSIPAMAS.FATKALEM_ADEDI, 
                         dbo.TBLSIPAMAS.SIPARIS_TEST, dbo.TBLSIPAMAS.TOPLAM_MIK, dbo.TBLSIPAMAS.TOPDEPO, dbo.TBLSIPAMAS.YEDEK22, dbo.TBLSIPAMAS.CARI_KOD2, dbo.TBLSIPAMAS.YEDEK, 
                         dbo.TBLSIPAMAS.UPDATE_KODU, dbo.TBLSIPAMAS.SIRANO, dbo.TBLSIPAMAS.KDV_DAHIL_BRUT_TOP, dbo.TBLSIPAMAS.KDV_TENZIL, dbo.TBLSIPAMAS.MALFAZLASIKDVSI, dbo.TBLSIPAMAS.GENELTOPLAM, 
                         dbo.TBLSIPAMAS.YUVARLAMA, dbo.TBLSIPAMAS.SATIS_KOND, dbo.TBLSIPAMAS.DOVIZTIP, dbo.TBLSIPAMAS.DOVIZTUT, dbo.TBLSIPAMAS.KS_KODU, dbo.TBLSIPAMAS.BAG_TUTAR, dbo.TBLSIPAMAS.YEDEK2, 
                         dbo.TBLSIPAMAS.HIZMET_FAT, dbo.TBLSIPAMAS.VADEBAZT, dbo.TBLSIPAMAS.KAPATILMIS, dbo.TBLSIPAMAS.S_YEDEK1, dbo.TBLSIPAMAS.S_YEDEK2, dbo.TBLSIPAMAS.F_YEDEK3, 
                         dbo.TBLSIPAMAS.F_YEDEK4, dbo.TBLSIPAMAS.F_YEDEK5, dbo.TBLSIPAMAS.C_YEDEK6, dbo.TBLSIPAMAS.B_YEDEK7, dbo.TBLSIPAMAS.I_YEDEK8, dbo.TBLSIPAMAS.L_YEDEK9, 
                         dbo.TBLSIPAMAS.AMBAR_KBLNO, dbo.TBLSIPAMAS.D_YEDEK10, dbo.TBLSIPAMAS.PROJE_KODU, dbo.TBLSIPAMAS.KOSULKODU, dbo.TBLSIPAMAS.FIYATTARIHI, dbo.TBLSIPAMAS.KOSULTARIHI, 
                         dbo.TBLSIPAMAS.GENISK1TIP, dbo.TBLSIPAMAS.GENISK2TIP, dbo.TBLSIPAMAS.GENISK3TIP, dbo.TBLSIPAMAS.EXPORTTYPE, dbo.TBLSIPAMAS.EXGUMRUKNO, dbo.TBLSIPAMAS.EXGUMTARIH, 
                         dbo.TBLSIPAMAS.EXFIILITARIH, dbo.TBLSIPAMAS.EXPORTREFNO, dbo.TBLSIPAMAS.KAYITYAPANKUL, dbo.TBLSIPAMAS.KAYITTARIHI, dbo.TBLSIPAMAS.DUZELTMEYAPANKUL, 
                         dbo.TBLSIPAMAS.DUZELTMETARIHI, dbo.TBLSIPAMAS.GELSUBE_KODU, dbo.TBLSIPAMAS.GITSUBE_KODU, dbo.TBLSIPAMAS.ONAYTIPI, dbo.TBLSIPAMAS.ONAYNUM, dbo.TBLSIPAMAS.ISLETME_KODU, 
                         dbo.TBLSIPAMAS.ODEKOD, dbo.TBLSIPAMAS.BRMALIYET, dbo.TBLSIPAMAS.KOSVADEGUNU, dbo.TBLSIPAMAS.YAPKOD, dbo.TBLSIPAMAS.GIB_FATIRS_NO, dbo.TBLSIPAMAS.EXTERNALAPPID, 
                         dbo.TBLSIPAMAS.EXTERNALREFID, dbo.TBLSIPAMAS.EBELGE, dbo.TBLSIPAMAS.HALFAT, dbo.TBLSIPAMAS.FAT_ALTM3, dbo.TBLSIPAMAS.DOVBAZTAR, dbo.TBLSIPAMAS.OTVTEVTUTAR, 
                         dbo.TBLSIPAMAS.TOPGIRDEPO, dbo.TBLSIPAMAS.BFORM, dbo.TBLSIPAMAS.TEVKIFATIADE, dbo.TBLCASABIT.CARI_ISIM, dbo.TBLCARIPLASIYER.PLASIYER_ACIKLAMA, dbo.TBLCARIPLASIYER.GRUPKODU, 
                         dbo.TBLCARIPLASIYER.ISIM, dbo.TBLSTHAR.FISNO, dbo.TBLSTHAR.D_YEDEK10 AS TESLI_TARIH
FROM            dbo.TBLSIPAMAS WITH (NOLOCK) LEFT OUTER JOIN
                         dbo.TBLSTHAR ON dbo.TBLSIPAMAS.FATIRS_NO = dbo.TBLSTHAR.STHAR_SIPNUM LEFT OUTER JOIN
                         dbo.TBLCARIPLASIYER ON dbo.TBLSIPAMAS.PLA_KODU = dbo.TBLCARIPLASIYER.PLASIYER_KODU LEFT OUTER JOIN
                         dbo.TBLCASABIT ON dbo.TBLSIPAMAS.CARI_KODU = dbo.TBLCASABIT.CARI_KOD
GROUP BY dbo.TBLSIPAMAS.PLA_KODU, dbo.TBLSIPAMAS.SUBE_KODU, dbo.TBLSIPAMAS.FTIRSIP, dbo.TBLSIPAMAS.FATIRS_NO, dbo.TBLSIPAMAS.CARI_KODU, dbo.TBLSIPAMAS.TARIH, dbo.TBLSIPAMAS.TIPI, 
                         dbo.TBLSIPAMAS.BRUTTUTAR, dbo.TBLSIPAMAS.SAT_ISKT, dbo.TBLSIPAMAS.MFAZ_ISKT, dbo.TBLSIPAMAS.GEN_ISK1T, dbo.TBLSIPAMAS.GEN_ISK2T, dbo.TBLSIPAMAS.GEN_ISK3T, 
                         dbo.TBLSIPAMAS.GEN_ISK1O, dbo.TBLSIPAMAS.GEN_ISK2O, dbo.TBLSIPAMAS.GEN_ISK3O, dbo.TBLSIPAMAS.KDV, dbo.TBLSIPAMAS.FAT_ALTM1, dbo.TBLSIPAMAS.FAT_ALTM2, dbo.TBLSIPAMAS.ACIKLAMA, 
                         dbo.TBLSIPAMAS.KOD1, dbo.TBLSIPAMAS.KOD2, dbo.TBLSIPAMAS.ODEMEGUNU, dbo.TBLSIPAMAS.ODEMETARIHI, dbo.TBLSIPAMAS.KDV_DAHILMI, dbo.TBLSIPAMAS.FATKALEM_ADEDI, 
                         dbo.TBLSIPAMAS.SIPARIS_TEST, dbo.TBLSIPAMAS.TOPLAM_MIK, dbo.TBLSIPAMAS.TOPDEPO, dbo.TBLSIPAMAS.YEDEK22, dbo.TBLSIPAMAS.CARI_KOD2, dbo.TBLSIPAMAS.YEDEK, 
                         dbo.TBLSIPAMAS.UPDATE_KODU, dbo.TBLSIPAMAS.SIRANO, dbo.TBLSIPAMAS.KDV_DAHIL_BRUT_TOP, dbo.TBLSIPAMAS.KDV_TENZIL, dbo.TBLSIPAMAS.MALFAZLASIKDVSI, dbo.TBLSIPAMAS.GENELTOPLAM, 
                         dbo.TBLSIPAMAS.YUVARLAMA, dbo.TBLSIPAMAS.SATIS_KOND, dbo.TBLSIPAMAS.DOVIZTIP, dbo.TBLSIPAMAS.DOVIZTUT, dbo.TBLSIPAMAS.KS_KODU, dbo.TBLSIPAMAS.BAG_TUTAR, dbo.TBLSIPAMAS.YEDEK2, 
                         dbo.TBLSIPAMAS.HIZMET_FAT, dbo.TBLSIPAMAS.VADEBAZT, dbo.TBLSIPAMAS.KAPATILMIS, dbo.TBLSIPAMAS.S_YEDEK1, dbo.TBLSIPAMAS.S_YEDEK2, dbo.TBLSIPAMAS.F_YEDEK3, 
                         dbo.TBLSIPAMAS.F_YEDEK4, dbo.TBLSIPAMAS.F_YEDEK5, dbo.TBLSIPAMAS.C_YEDEK6, dbo.TBLSIPAMAS.B_YEDEK7, dbo.TBLSIPAMAS.I_YEDEK8, dbo.TBLSIPAMAS.L_YEDEK9, 
                         dbo.TBLSIPAMAS.AMBAR_KBLNO, dbo.TBLSIPAMAS.D_YEDEK10, dbo.TBLSIPAMAS.PROJE_KODU, dbo.TBLSIPAMAS.KOSULKODU, dbo.TBLSIPAMAS.FIYATTARIHI, dbo.TBLSIPAMAS.KOSULTARIHI, 
                         dbo.TBLSIPAMAS.GENISK1TIP, dbo.TBLSIPAMAS.GENISK2TIP, dbo.TBLSIPAMAS.GENISK3TIP, dbo.TBLSIPAMAS.EXPORTTYPE, dbo.TBLSIPAMAS.EXGUMRUKNO, dbo.TBLSIPAMAS.EXGUMTARIH, 
                         dbo.TBLSIPAMAS.EXFIILITARIH, dbo.TBLSIPAMAS.EXPORTREFNO, dbo.TBLSIPAMAS.KAYITYAPANKUL, dbo.TBLSIPAMAS.KAYITTARIHI, dbo.TBLSIPAMAS.DUZELTMEYAPANKUL, 
                         dbo.TBLSIPAMAS.DUZELTMETARIHI, dbo.TBLSIPAMAS.GELSUBE_KODU, dbo.TBLSIPAMAS.GITSUBE_KODU, dbo.TBLSIPAMAS.ONAYTIPI, dbo.TBLSIPAMAS.ONAYNUM, dbo.TBLSIPAMAS.ISLETME_KODU, 
                         dbo.TBLSIPAMAS.ODEKOD, dbo.TBLSIPAMAS.BRMALIYET, dbo.TBLSIPAMAS.KOSVADEGUNU, dbo.TBLSIPAMAS.YAPKOD, dbo.TBLSIPAMAS.GIB_FATIRS_NO, dbo.TBLSIPAMAS.EXTERNALAPPID, 
                         dbo.TBLSIPAMAS.EXTERNALREFID, dbo.TBLSIPAMAS.EBELGE, dbo.TBLSIPAMAS.HALFAT, dbo.TBLSIPAMAS.FAT_ALTM3, dbo.TBLSIPAMAS.DOVBAZTAR, dbo.TBLSIPAMAS.OTVTEVTUTAR, 
                         dbo.TBLSIPAMAS.TOPGIRDEPO, dbo.TBLSIPAMAS.BFORM, dbo.TBLSIPAMAS.TEVKIFATIADE, dbo.TBLCASABIT.CARI_ISIM, dbo.TBLCARIPLASIYER.PLASIYER_ACIKLAMA, dbo.TBLCARIPLASIYER.GRUPKODU, 
                         dbo.TBLCARIPLASIYER.ISIM, dbo.TBLSTHAR.FISNO, dbo.TBLSTHAR.D_YEDEK10
");
            #endregion

            #region BSD_SIPARIS_TESLIM_STOK_ANA
              Sql(@"CREATE VIEW [dbo].[BSD_SIPARIS_TESLIM_STOK_ANA]
AS
SELECT        dbo.TBLSTSABIT.STOK_ADI, dbo.TBLSIPATRA.STHAR_GCMIK, dbo.TBLCARIPLASIYER.PLASIYER_ACIKLAMA, dbo.TBLCARIPLASIYER.GRUPKODU, dbo.TBLCARIPLASIYER.PLASIYER_KODU, 
                         dbo.TBLSIPAMAS.FTIRSIP, dbo.TBLSIPAMAS.FATIRS_NO, dbo.TBLSIPAMAS.CARI_KODU, dbo.TBLSIPAMAS.TARIH, dbo.TBLSIPAMAS.TIPI, dbo.TBLSIPAMAS.BRUTTUTAR, dbo.TBLSIPAMAS.ODEMEGUNU, 
                         dbo.TBLSIPAMAS.ODEMETARIHI, dbo.TBLSIPAMAS.SIPARIS_TEST, dbo.TBLSIPATRA.STOK_KODU, dbo.TBLSTSABIT.URETICI_KODU, dbo.TBLSIPATRA.STHAR_DOVFIAT, dbo.TBLSIPATRA.STHAR_DOVTIP, 
                         dbo.TBLSIPATRA.FIRMA_DOVTUT AS TESLIM_MIK, dbo.TBLSIPATRA.INCKEYNO, dbo.TBLSIPATRA.SIRA, dbo.TBLCASABIT.CARI_ISIM, dbo.TBLCASABIT.CARI_KOD, dbo.TBLSIPATRA.STHAR_NF, 
                         dbo.TBLSIPATRA.STHAR_BF, dbo.TBLSIPATRA.STHAR_HTUR
FROM            dbo.TBLCARIPLASIYER RIGHT OUTER JOIN
                         dbo.TBLCASABIT RIGHT OUTER JOIN
                         dbo.TBLSIPAMAS ON dbo.TBLCASABIT.CARI_KOD = dbo.TBLSIPAMAS.CARI_KODU ON dbo.TBLCARIPLASIYER.PLASIYER_KODU = dbo.TBLSIPAMAS.PLA_KODU LEFT OUTER JOIN
                         dbo.TBLSTSABIT RIGHT OUTER JOIN
                         dbo.TBLSIPATRA ON dbo.TBLSTSABIT.STOK_KODU = dbo.TBLSIPATRA.STOK_KODU ON dbo.TBLSIPAMAS.FATIRS_NO = dbo.TBLSIPATRA.FISNO
");
            #endregion

            #region BSD_SIPARIS_TESLIM_STOK
              Sql(@"CREATE VIEW [dbo].[BSD_SIPARIS_TESLIM_STOK]
AS
SELECT        dbo.BSD_SIPARIS_TESLIM_STOK_ANA.STOK_ADI, dbo.BSD_SIPARIS_TESLIM_STOK_ANA.STHAR_GCMIK, dbo.BSD_SIPARIS_TESLIM_STOK_ANA.PLASIYER_ACIKLAMA, 
                         dbo.BSD_SIPARIS_TESLIM_STOK_ANA.GRUPKODU, dbo.BSD_SIPARIS_TESLIM_STOK_ANA.PLASIYER_KODU, dbo.BSD_SIPARIS_TESLIM_STOK_ANA.FTIRSIP, 
                         dbo.BSD_SIPARIS_TESLIM_STOK_ANA.FATIRS_NO, dbo.BSD_SIPARIS_TESLIM_STOK_ANA.CARI_KODU, dbo.BSD_SIPARIS_TESLIM_STOK_ANA.TARIH, dbo.BSD_SIPARIS_TESLIM_STOK_ANA.TIPI, 
                         dbo.BSD_SIPARIS_TESLIM_STOK_ANA.BRUTTUTAR, dbo.BSD_SIPARIS_TESLIM_STOK_ANA.ODEMEGUNU, dbo.BSD_SIPARIS_TESLIM_STOK_ANA.ODEMETARIHI, 
                         dbo.BSD_SIPARIS_TESLIM_STOK_ANA.SIPARIS_TEST, dbo.BSD_SIPARIS_TESLIM_STOK_ANA.STOK_KODU, dbo.BSD_SIPARIS_TESLIM_STOK_ANA.URETICI_KODU, 
                         dbo.BSD_SIPARIS_TESLIM_STOK_ANA.STHAR_DOVFIAT, dbo.BSD_SIPARIS_TESLIM_STOK_ANA.STHAR_DOVTIP, dbo.BSD_SIPARIS_TESLIM_STOK_ANA.TESLIM_MIK, dbo.TBLSTHAR.FISNO, 
                         dbo.TBLSTHAR.STHAR_SIPNUM, dbo.TBLSTHAR.D_YEDEK10 AS TESLIM_TARIHI, dbo.BSD_SIPARIS_TESLIM_STOK_ANA.INCKEYNO, dbo.BSD_SIPARIS_TESLIM_STOK_ANA.CARI_ISIM, 
                         dbo.BSD_SIPARIS_TESLIM_STOK_ANA.CARI_KOD, dbo.BSD_SIPARIS_TESLIM_STOK_ANA.STHAR_NF, dbo.BSD_SIPARIS_TESLIM_STOK_ANA.STHAR_BF, dbo.TBLSTHAR.STHAR_GCMIK AS HAR_STHAR_GCMIK, 
                         dbo.BSD_SIPARIS_TESLIM_STOK_ANA.STHAR_HTUR
FROM            dbo.BSD_SIPARIS_TESLIM_STOK_ANA LEFT OUTER JOIN
                         dbo.TBLSTHAR ON dbo.BSD_SIPARIS_TESLIM_STOK_ANA.SIRA = dbo.TBLSTHAR.STRA_SIPKONT AND dbo.BSD_SIPARIS_TESLIM_STOK_ANA.STOK_KODU = dbo.TBLSTHAR.STOK_KODU AND 
                         dbo.BSD_SIPARIS_TESLIM_STOK_ANA.FATIRS_NO = dbo.TBLSTHAR.STHAR_SIPNUM
GROUP BY dbo.BSD_SIPARIS_TESLIM_STOK_ANA.STOK_ADI, dbo.BSD_SIPARIS_TESLIM_STOK_ANA.PLASIYER_ACIKLAMA, dbo.BSD_SIPARIS_TESLIM_STOK_ANA.GRUPKODU, 
                         dbo.BSD_SIPARIS_TESLIM_STOK_ANA.PLASIYER_KODU, dbo.BSD_SIPARIS_TESLIM_STOK_ANA.FTIRSIP, dbo.BSD_SIPARIS_TESLIM_STOK_ANA.FATIRS_NO, 
                         dbo.BSD_SIPARIS_TESLIM_STOK_ANA.CARI_KODU, dbo.BSD_SIPARIS_TESLIM_STOK_ANA.TARIH, dbo.BSD_SIPARIS_TESLIM_STOK_ANA.TIPI, dbo.BSD_SIPARIS_TESLIM_STOK_ANA.BRUTTUTAR, 
                         dbo.BSD_SIPARIS_TESLIM_STOK_ANA.ODEMEGUNU, dbo.BSD_SIPARIS_TESLIM_STOK_ANA.ODEMETARIHI, dbo.BSD_SIPARIS_TESLIM_STOK_ANA.SIPARIS_TEST, 
                         dbo.BSD_SIPARIS_TESLIM_STOK_ANA.STOK_KODU, dbo.BSD_SIPARIS_TESLIM_STOK_ANA.URETICI_KODU, dbo.BSD_SIPARIS_TESLIM_STOK_ANA.STHAR_DOVFIAT, 
                         dbo.BSD_SIPARIS_TESLIM_STOK_ANA.STHAR_DOVTIP, dbo.BSD_SIPARIS_TESLIM_STOK_ANA.TESLIM_MIK, dbo.TBLSTHAR.FISNO, dbo.TBLSTHAR.STHAR_SIPNUM, dbo.TBLSTHAR.D_YEDEK10, 
                         dbo.BSD_SIPARIS_TESLIM_STOK_ANA.STHAR_GCMIK, dbo.BSD_SIPARIS_TESLIM_STOK_ANA.INCKEYNO, dbo.BSD_SIPARIS_TESLIM_STOK_ANA.CARI_ISIM, dbo.BSD_SIPARIS_TESLIM_STOK_ANA.CARI_KOD, 
                         dbo.BSD_SIPARIS_TESLIM_STOK_ANA.STHAR_NF, dbo.BSD_SIPARIS_TESLIM_STOK_ANA.STHAR_BF, dbo.TBLSTHAR.STHAR_GCMIK, dbo.BSD_SIPARIS_TESLIM_STOK_ANA.STHAR_HTUR
");
            #endregion

            #region BSD_SATIS_TEKLIF
              Sql(@"CREATE VIEW [dbo].[BSD_SATIS_TEKLIF]
AS
SELECT        dbo.TBLTEKLIFMAS.FTIRSIP, dbo.TBLTEKLIFMAS.FATIRS_NO, dbo.TBLTEKLIFMAS.CARI_KODU, dbo.TBLTEKLIFMAS.TARIH, dbo.TBLTEKLIFMAS.TIPI, dbo.TBLTEKLIFMAS.BRUTTUTAR, 
                         dbo.TBLTEKLIFMAS.SAT_ISKT, dbo.TBLTEKLIFMAS.MFAZ_ISKT, dbo.TBLTEKLIFMAS.SIPARIS_TEST, dbo.TBLTEKLIFMAS.GENELTOPLAM, dbo.TBLTEKLIFMAS.PLA_KODU, dbo.TBLTEKLIFMAS.DOVIZTIP, 
                         dbo.TBLTEKLIFMAS.DOVIZTUT, dbo.TBLTEKLIFMAS.D_YEDEK10, dbo.TBLTEKLIFTRA.STOK_KODU, SUM(dbo.TBLTEKLIFTRA.STHAR_GCMIK) AS T_STHAR_GCMIK, dbo.TBLTEKLIFTRA.STHAR_GCKOD, 
                         dbo.TBLTEKLIFTRA.STHAR_TARIH, dbo.TBLTEKLIFTRA.STHAR_NF, dbo.TBLTEKLIFTRA.STHAR_BF, dbo.TBLTEKLIFTRA.STHAR_IAF, dbo.TBLTEKLIFTRA.STHAR_KDV, dbo.TBLTEKLIFTRA.DEPO_KODU, 
                         dbo.TBLTEKLIFTRA.STHAR_DOVTIP, dbo.TBLTEKLIFTRA.STHAR_DOVFIAT, dbo.TBLTEKLIFTRA.STHAR_ODEGUN, dbo.TBLTEKLIFTRA.EKALAN, dbo.TBLTEKLIFTRA.STHAR_TESTAR, 
                         dbo.TBLTEKLIFTRA.VADE_TARIHI, dbo.TBLTEKLIFTRA.D_YEDEK10 AS S_D_YEDEK10, dbo.TBLCARIPLASIYER.PLASIYER_ACIKLAMA, dbo.TBLSTSABIT.STOK_ADI, 
                         dbo.TBLSIPATRA.STOK_KODU AS S_STOK_KODU, dbo.TBLSIPATRA.IRSALIYE_NO, SUM(dbo.TBLSIPATRA.STHAR_GCMIK) AS S_STHAR_GCMIK, dbo.TBLSIPATRA.STHAR_GCKOD AS S_STHAR_GCKOD, 
                         dbo.TBLSIPATRA.STHAR_TARIH AS S_STHAR_TARIH, dbo.TBLSIPATRA.STHAR_NF AS S_STHAR_NF, dbo.TBLSIPATRA.STHAR_BF AS S_STHAR_BF, dbo.TBLSIPATRA.STHAR_IAF AS S_STHAR_IAF, 
                         dbo.TBLSIPATRA.STHAR_KDV AS Expr8, dbo.TBLSIPATRA.DEPO_KODU AS S_DEPO_KODU, dbo.TBLSIPATRA.STHAR_DOVTIP AS S_STHAR_DOVTIP, dbo.TBLSIPATRA.STHAR_DOVFIAT AS S_STHAR_DOVFIAT, 
                         dbo.TBLSIPATRA.STHAR_ODEGUN AS S_STHAR_ODEGUN, dbo.TBLSIPATRA.EKALAN AS S_EKALAN, dbo.TBLCASABIT.CARI_ISIM, dbo.TBLTEKLIFTRA.IRS_INCKEYNO
FROM            dbo.TBLCARIPLASIYER RIGHT OUTER JOIN
                         dbo.TBLCASABIT RIGHT OUTER JOIN
                         dbo.TBLTEKLIFMAS ON dbo.TBLCASABIT.CARI_KOD = dbo.TBLTEKLIFMAS.CARI_KODU ON dbo.TBLCARIPLASIYER.PLASIYER_KODU = dbo.TBLTEKLIFMAS.PLA_KODU LEFT OUTER JOIN
                         dbo.TBLSIPATRA RIGHT OUTER JOIN
                         dbo.TBLTEKLIFTRA ON dbo.TBLSIPATRA.STOK_KODU = dbo.TBLTEKLIFTRA.STOK_KODU AND dbo.TBLSIPATRA.IRSALIYE_NO = dbo.TBLTEKLIFTRA.FISNO LEFT OUTER JOIN
                         dbo.TBLSTSABIT ON dbo.TBLTEKLIFTRA.STOK_KODU = dbo.TBLSTSABIT.STOK_KODU ON dbo.TBLTEKLIFMAS.FATIRS_NO = dbo.TBLTEKLIFTRA.FISNO
GROUP BY dbo.TBLTEKLIFMAS.FTIRSIP, dbo.TBLTEKLIFMAS.FATIRS_NO, dbo.TBLTEKLIFMAS.CARI_KODU, dbo.TBLTEKLIFMAS.TARIH, dbo.TBLTEKLIFMAS.TIPI, dbo.TBLTEKLIFMAS.BRUTTUTAR, 
                         dbo.TBLTEKLIFMAS.SAT_ISKT, dbo.TBLTEKLIFMAS.MFAZ_ISKT, dbo.TBLTEKLIFMAS.SIPARIS_TEST, dbo.TBLTEKLIFMAS.GENELTOPLAM, dbo.TBLTEKLIFMAS.PLA_KODU, dbo.TBLTEKLIFMAS.DOVIZTIP, 
                         dbo.TBLTEKLIFMAS.DOVIZTUT, dbo.TBLTEKLIFMAS.D_YEDEK10, dbo.TBLTEKLIFTRA.STOK_KODU, dbo.TBLTEKLIFTRA.STHAR_GCKOD, dbo.TBLTEKLIFTRA.STHAR_TARIH, dbo.TBLTEKLIFTRA.STHAR_NF, 
                         dbo.TBLTEKLIFTRA.STHAR_BF, dbo.TBLTEKLIFTRA.STHAR_IAF, dbo.TBLTEKLIFTRA.STHAR_KDV, dbo.TBLTEKLIFTRA.DEPO_KODU, dbo.TBLTEKLIFTRA.STHAR_DOVTIP, dbo.TBLTEKLIFTRA.STHAR_DOVFIAT, 
                         dbo.TBLTEKLIFTRA.STHAR_ODEGUN, dbo.TBLTEKLIFTRA.EKALAN, dbo.TBLTEKLIFTRA.STHAR_TESTAR, dbo.TBLTEKLIFTRA.VADE_TARIHI, dbo.TBLTEKLIFTRA.D_YEDEK10, 
                         dbo.TBLCARIPLASIYER.PLASIYER_ACIKLAMA, dbo.TBLSTSABIT.STOK_ADI, dbo.TBLSIPATRA.STOK_KODU, dbo.TBLSIPATRA.IRSALIYE_NO, dbo.TBLSIPATRA.STHAR_GCKOD, dbo.TBLSIPATRA.STHAR_TARIH, 
                         dbo.TBLSIPATRA.STHAR_NF, dbo.TBLSIPATRA.STHAR_BF, dbo.TBLSIPATRA.STHAR_IAF, dbo.TBLSIPATRA.STHAR_KDV, dbo.TBLSIPATRA.DEPO_KODU, dbo.TBLSIPATRA.STHAR_DOVTIP, 
                         dbo.TBLSIPATRA.STHAR_DOVFIAT, dbo.TBLSIPATRA.STHAR_ODEGUN, dbo.TBLSIPATRA.EKALAN, dbo.TBLCASABIT.CARI_ISIM, dbo.TBLTEKLIFTRA.IRS_INCKEYNO
HAVING        (dbo.TBLTEKLIFMAS.FTIRSIP = 'H') AND (dbo.TBLTEKLIFTRA.STOK_KODU <> '600-001-0012')
");
            #endregion

            #region BSD_SON_GIRIS_FIYATLARI
             Sql(@"CREATE VIEW [dbo].[BSD_SON_GIRIS_FIYATLARI]
AS
SELECT        STOK_KODU, STHAR_HTUR,
                             (SELECT        ISNULL(SUM(STHAR_BF) / COUNT(STHAR_BF), 0) AS Expr1
                               FROM            dbo.TBLSTHAR
                               WHERE        (STHAR_TARIH = MAX(bas.STHAR_TARIH)) AND (STOK_KODU = bas.STOK_KODU) AND (STHAR_GCKOD = 'G') AND (STHAR_HTUR IN ('J'))) AS SON_GIR_FIYAT,
                             (SELECT        ISNULL(SUM(STHAR_DOVFIAT) / COUNT(STHAR_DOVFIAT), 0) AS Expr1
                               FROM            dbo.TBLSTHAR AS TBLSTHAR_1
                               WHERE        (STHAR_TARIH = MAX(bas.STHAR_TARIH)) AND (STOK_KODU = bas.STOK_KODU) AND (STHAR_GCKOD = 'G') AND (STHAR_HTUR IN ('J'))) AS SON_GIR_DOV,
                             (SELECT        MIN(STHAR_DOVTIP) AS Expr1
                               FROM            dbo.TBLSTHAR AS TBLSTHAR_1
                               WHERE        (STHAR_TARIH = MAX(bas.STHAR_TARIH)) AND (STOK_KODU = bas.STOK_KODU) AND (STHAR_GCKOD = 'G') AND (STHAR_HTUR IN ('J'))
                               GROUP BY STHAR_TARIH, STOK_KODU, STHAR_GCKOD, STHAR_HTUR) AS STHAR_DOVTIP
FROM            dbo.TBLSTHAR AS bas
GROUP BY STOK_KODU, STHAR_GCKOD, STHAR_HTUR
HAVING        (STHAR_GCKOD = 'G') AND (STHAR_HTUR = 'J')
");
            #endregion

            #region BSD_ODEME_PLANI
            Sql(@"CREATE VIEW [dbo].[BSD_ODEME_PLANI]
AS
select VADETRH,'CEK' AS OdemeTuru,SC_NO,VEREN_CARI,VEREN_CARI_ISIM,VERILEN_CARI,VERILEN_CARI_ISIM,TUTAR,KURISIM,BANKA_YER,TIPI from BSD_VW_CEKSEN_SONISLEM where   VADETRH >= GETDATE()
UNION ALL
SELECT Tarih,OdemeTuru,BelgeNo,'','',CariKod,CariAdi,Tutar,OdemeTipi,BankaAdi,Aciklama FROM BSD_TBL_ODEME");
            #endregion

            #region BSD_VW_ISEMIRLERI
             Sql(@"SELECT        dbo.TBLSTSABIT.STOK_ADI, dbo.TBLISEMRIEK.*, dbo.TBLISEMRI.*
FROM            dbo.TBLISEMRI LEFT OUTER JOIN
                         dbo.TBLSTSABIT ON dbo.TBLISEMRI.STOK_KODU = dbo.TBLSTSABIT.STOK_KODU LEFT OUTER JOIN
                         dbo.TBLISEMRIEK ON dbo.TBLISEMRI.ISEMRINO = dbo.TBLISEMRIEK.ISEMRI");
            #endregion

            #region ZZZ_BANK_BAKIYE
              Sql(@"Create     VIEW [dbo].[ZZZ_BANK_BAKIYE]
AS
SELECT        NETHESKODU, REPLACE(REPLACE(REPLACE(ACIKLAMA, 'Þ', 'Ş'), 'Ý', 'İ'), 'Ð', 'G') AS ACIKLAMA, DOVIZTIPI, BANKAHESNO, HESBORCTOPDOV, HESALACTOPDOV, 
                         CASE WHEN HESALACTOPDOV - HESBORCTOPDOV < 0 AND DOVIZTIPI != 0 THEN HESBORCTOPDOV - HESALACTOPDOV ELSE 0 END AS BORCBAKIYEDOVIZ, 
                         CASE WHEN HESALACTOPDOV - HESBORCTOPDOV > 0 AND DOVIZTIPI != 0 THEN HESALACTOPDOV - HESBORCTOPDOV ELSE 0 END AS ALACAKBAKIYEDOVIZ, 
                         CASE WHEN HESALACTOP - HESBORCTOP < 0 THEN HESBORCTOP - HESALACTOP ELSE 0 END AS BORCBAKIYE, 
                         CASE WHEN HESALACTOP - HESBORCTOP > 0 THEN HESALACTOP - HESBORCTOP ELSE 0 END AS ALACAKBAKIYE, 
                         CASE WHEN DOVIZTIPI != 0 THEN HESBORCTOPDOV - HESALACTOPDOV ELSE (CASE WHEN DOVIZTIPI = 0 THEN HESALACTOP - HESBORCTOP ELSE (CASE WHEN DOVIZTIPI != 0 THEN HESBORCTOPDOV - HESALACTOPDOV
                          ELSE '0' END) END) END AS BAKIYE, HESAPTIPI,                         
						 CASE 
						    WHEN RAPORKODU = 'VSM' THEN 'Vadesiz Mevduat' 
							WHEN RAPORKODU = 'VLM' THEN 'Vadeli Mevduat' 
							WHEN RAPORKODU = 'RPO' THEN 'Repo' 
							WHEN RAPORKODU = 'TMC' THEN 'Teminat Cekleri' 
							WHEN RAPORKODU = 'TMS' THEN 'Teminat Senetleri' 
							WHEN RAPORKODU = 'THC' THEN 'Tahsil Cekleri' 
							WHEN RAPORKODU = 'THS' THEN 'Tahsil Senetleri' 
							WHEN RAPORKODU = 'CKR' THEN 'Nakit Kredi Borclu Cari Kredi Rotatif' 
							WHEN RAPORKODU = 'NKS' THEN 'Nakit Kredi Spot'
							WHEN RAPORKODU = 'NKI' THEN 'Nakit Kredi Iskonto_Istira' 
							WHEN RAPORKODU = 'GTM' THEN 'Gayri Nakdi Kredi Teminat Mektubu' 
							WHEN RAPORKODU = 'GHG' THEN 'Gayri Nakdi Kredi Harici Garanti' 
							WHEN RAPORKODU = 'GIA' THEN 'Gayri Nakdi Kredi Ithalat Akreditifi' 
							WHEN RAPORKODU = 'GKA' THEN 'Gayri Nakdi Kredi Kabul Ve Aval' 
							WHEN RAPORKODU = 'KKH' THEN 'Kredi Karti Hesabi Pos' 
							WHEN RAPORKODU = 'THK' THEN 'Taksitli Kredi' 
							WHEN RAPORKODU = 'UVK' THEN 'Uzun VadeliKredi' 
							WHEN RAPORKODU = 'BRC' THEN 'Borc Cekleri' 
							WHEN RAPORKODU = 'BRS' THEN 'Borc Senetleri'
							WHEN RAPORKODU = 'KRH' THEN 'Kredi Kartı Hesabı'
							WHEN RAPORKODU = 'DBS' THEN 'Doğrudan Borçlanma Sistemi'
							WHEN RAPORKODU = 'FKK' THEN 'Firma Kredi Kartı'  
							WHEN RAPORKODU = 'POS' THEN 'POS HESABI'  
							ELSE 'DigerHesap' END AS HESAPTIPLERI, RAPORKODU
FROM            dbo.TBLBNKHESSABIT");
            #endregion

            #region ZZZ_STOK_HAR_AYRINTI
              Sql(@"CREATE VIEW [dbo].[ZZZ_STOK_HAR_AYRINTI]
AS
SELECT        dbo.TBLSTHAR.STOK_KODU, REPLACE(REPLACE(REPLACE(dbo.TBLSTSABIT.STOK_ADI, 'Þ', 'Ş'), 'Ý', 'İ'), 'Ð', 'G') AS STOK_ADI, REPLACE(REPLACE(REPLACE(dbo.TBLCASABIT.CARI_ISIM, 'Þ', 'Ş'), 'Ý', 'İ'), 'Ð', 'G') AS CARI_ISIM, 
                         REPLACE(REPLACE(REPLACE(dbo.TBLCASABIT.CARI_IL, 'Þ', 'Ş'), 'Ý', 'İ'), 'Ð', 'G') AS CARI_IL, dbo.TBLSTHAR.FISNO, dbo.TBLSTHAR.STHAR_TARIH, dbo.TBLSTHAR.STHAR_NF, dbo.TBLSTHAR.STHAR_BF, 
                         dbo.TBLSTHAR.STHAR_GCMIK, dbo.TBLSTHAR.STHAR_GCMIK * dbo.TBLSTHAR.STHAR_BF AS TOPLAM, dbo.TBLSTHAR.STHAR_FTIRSIP, dbo.TBLSTHAR.STHAR_HTUR, 
                         CASE WHEN dbo.TBLSTHAR.STHAR_FTIRSIP = '1' THEN 'SatisFaturasi' WHEN dbo.TBLSTHAR.STHAR_FTIRSIP = '2' THEN 'AlisFaturasi' WHEN dbo.TBLSTHAR.STHAR_FTIRSIP = '3' THEN 'SatisiRsaliyesi' WHEN dbo.TBLSTHAR.STHAR_FTIRSIP
                          = '4' THEN 'Alisirsaliyesi' WHEN dbo.TBLSTHAR.STHAR_FTIRSIP = '6' THEN 'MusteriSiparisi' ELSE 'Bilinmiyor' END AS HESAPTIPLERI, dbo.TBLSTSABIT.GRUP_KODU, dbo.TBLSTSABIT.KOD_1, NEWID() AS ID, 
                         dbo.TBLSTSABIT.ALIS_FIAT1
FROM            dbo.TBLSTHAR LEFT OUTER JOIN
                         dbo.TBLSTSABIT ON dbo.TBLSTHAR.STOK_KODU = dbo.TBLSTSABIT.STOK_KODU LEFT OUTER JOIN
                         dbo.TBLCASABIT ON dbo.TBLSTHAR.STHAR_CARIKOD = dbo.TBLCASABIT.CARI_KOD");
            #endregion

            #region ZZZ_FATURASB
              Sql(@"Create   VIEW [dbo].[ZZZ_FATURASB]
AS
SELECT        dbo.TBLFATUIRS.SUBE_KODU, dbo.TBLFATUIRS.CARI_KODU, REPLACE(REPLACE(REPLACE(dbo.TBLCASABIT.CARI_ISIM, 'Þ', 'Ş'), 'Ý', 'İ'), 'Ð', 'G') AS CARI_ISIM, dbo.TBLFATUIRS.KDV, dbo.TBLFATUIRS.FTIRSIP, 
                         dbo.TBLFATUIRS.TIPI, dbo.TBLFATUIRS.ODEMETARIHI, dbo.TBLFATUIRS.DOVIZTIP, dbo.TBLFATUIRS.DOVIZTUT, dbo.TBLFATUIRS.BRUTTUTAR, dbo.TBLFATUIRS.FATIRS_NO, dbo.TBLFATUIRS.TARIH, 
                         dbo.TBLFATUIRS.GENELTOPLAM, ISNULL(KUR.ISIM, '') AS KURISIM, ISNULL(dbo.TBLFATUIRS.YEDEK, '') AS DAT, dbo.TBLFATUIRS.PLA_KODU AS PLASIYER_KODU, (CASE WHEN ISNULL(FTIRSIP, '') 
                         = '1' THEN (CASE WHEN ISNULL(TIPI, '') = '2' THEN 'Satış Faturası' WHEN ISNULL(TIPI, '') = '4' THEN 'İade Satış Faturası' END) WHEN ISNULL(FTIRSIP, '') = '2' THEN (CASE WHEN ISNULL(TIPI, '') 
                         = '2' THEN 'Alış Faturası' WHEN ISNULL(TIPI, '') = '4' THEN 'İade Alış   Faturası' END) WHEN ISNULL(FTIRSIP, '') = '3' THEN (CASE WHEN ISNULL(TIPI, '') = '2' THEN 'Satış Irsaliyesi' WHEN ISNULL(TIPI, '') 
                         = '4' THEN 'İade Satış Irsaliyesi' END) WHEN ISNULL(FTIRSIP, '') = '4' THEN (CASE WHEN ISNULL(TIPI, '') = '2' THEN 'Alış Irsaliyesi' WHEN ISNULL(TIPI, '') = '4' THEN 'İade Alış Irsaliyesi' END) WHEN ISNULL(FTIRSIP, '') 
                         = '8' THEN (CASE WHEN ISNULL(YEDEK, '') = 'D' THEN 'Depo Çıkış' ELSE 'Ambar Çıkış' END) WHEN ISNULL(FTIRSIP, '') = '9' THEN (CASE WHEN ISNULL(YEDEK, '') = 'D' THEN 'Depo Giriş' ELSE 'Ambar Giriş' END) 
                         ELSE '' END) AS BELGE_TURU, dbo.TBLFATUIRS.GEN_ISK1T + dbo.TBLFATUIRS.GEN_ISK2T + dbo.TBLFATUIRS.GEN_ISK3T AS GENEL_ISKONTO, dbo.TBLFATUIRS.SAT_ISKT, NEWID() AS ID
FROM            dbo.TBLFATUIRS LEFT OUTER JOIN
                         dbo.TBLCASABIT ON dbo.TBLFATUIRS.CARI_KODU = dbo.TBLCASABIT.CARI_KOD LEFT OUTER JOIN
                         NETSIS.dbo.KUR AS KUR ON KUR.SIRA = dbo.TBLFATUIRS.DOVIZTIP
WHERE        (ISNULL(dbo.TBLFATUIRS.FTIRSIP, '') NOT IN ('B', 'A')) AND (dbo.TBLFATUIRS.TARIH >= '20070828')");
            #endregion

            #region ZZZ_CARI_EKSTRE
              Sql(@"Create   VIEW [dbo].[ZZZ_CARI_EKSTRE]
AS
SELECT        dbo.TBLCAHAR.CARI_KOD, dbo.TBLCAHAR.TARIH, dbo.TBLCAHAR.BELGE_NO, REPLACE(REPLACE(REPLACE(SUBSTRING(dbo.TBLCAHAR.ACIKLAMA, 1, 40), 'Þ', 'Ş'), 'Ý', 'İ'), 'Ð', 'Ğ') AS ACIKLAMA, 
                         dbo.TBLCAHAR.VADE_TARIHI, dbo.TBLCAHAR.BORC, dbo.TBLCAHAR.ALACAK, dbo.TBLCAHAR.BORC - dbo.TBLCAHAR.ALACAK AS BAKIYE, REPLACE(REPLACE(REPLACE(dbo.TBLCASABIT.CARI_IL, 'Þ', 'Ş'), 'Ý', 'İ'), 'Ð', 'Ğ') 
                         AS CARI_IL, REPLACE(REPLACE(REPLACE(dbo.TBLCASABIT.CARI_ISIM, 'Þ', 'Ş'), 'Ý', 'İ'), 'Ð', 'Ğ') AS CARI_ISIM, dbo.TBLCAHAR.HAREKET_TURU, 
                         CASE dbo.TBLCAHAR.HAREKET_TURU WHEN 'A' THEN 'Devir' WHEN 'K' THEN 'Dekont' WHEN 'D' THEN 'Kasa' WHEN 'G' THEN 'Müşteri Çeki' WHEN 'H' THEN 'Borç Çeki' WHEN 'E' THEN 'Müşteri Seneti' WHEN 'B' THEN 'Fatura'
                          WHEN 'L' THEN 'Muhtelif' WHEN 'C' THEN 'Iade Faturası' WHEN 'I' THEN 'Protesto Seneti' ELSE 'DIGER' END AS TIP, NEWID() AS ID
FROM            dbo.TBLCAHAR INNER JOIN
                         dbo.TBLCASABIT ON dbo.TBLCAHAR.CARI_KOD = dbo.TBLCASABIT.CARI_KOD");
            #endregion

            #region ZZZ_KASAHAR
              Sql(@"Create   VIEW [dbo].[ZZZ_KASAHAR]
AS
SELECT        dbo.TBLKASA.KSMAS_KOD, dbo.TBLKASA.TARIH, dbo.TBLKASA.FISNO, dbo.TBLKASA.IO, REPLACE(REPLACE(REPLACE(dbo.TBLKASA.TIP, 'C', 'CARI'), 'M', 'MUHTELIF'), 'B', 'BANKA') AS TIP, 
                         REPLACE(REPLACE(REPLACE(dbo.TBLKASA.ACIKLAMA, 'Þ', 'Ş'), 'Ý', 'İ'), 'Ð', 'G') AS ACIKLAMA, dbo.TBLKASA.TUTAR, dbo.TBLKASA.DOVIZTUT, dbo.TBLKASA.KUR, dbo.TBLKASA.KOD, 
                         dbo.TBLKASAMAS.KSMAS_NAME, CASE WHEN IO = 'C' THEN dbo.TBLKASA.TUTAR ELSE 0 END AS CIKIS, CASE WHEN IO = 'G' THEN dbo.TBLKASA.TUTAR ELSE 0 END AS GIRIS, NEWID() AS ID, 
                         dbo.TBLKASAMAS.DOVIZLI, dbo.TBLKASAMAS.DOVIZTIPI
FROM            dbo.TBLKASA INNER JOIN
                         dbo.TBLKASAMAS ON dbo.TBLKASA.KSMAS_KOD = dbo.TBLKASAMAS.KSMAS_KOD");
            #endregion

            #region ZZZ_MUH_GIDER
              Sql(@"Create   VIEW [dbo].[ZZZ_MUH_GIDER]
AS
SELECT        AY_KODU, TARIH, REPLACE(REPLACE(REPLACE
                             ((SELECT        HS_ADI
                                 FROM            dbo.TBLMUPLAN
                                 WHERE        (HESAP_KODU = M.HES_KOD)), 'Þ', 'Ş'), 'Ý', 'İ'), 'Ð', 'G') AS HS_ADI,
                             (SELECT        HS_ADI
                               FROM            dbo.TBLMUPLAN AS TBLMUPLAN_2
                               WHERE        (HESAP_KODU = SUBSTRING(M.HES_KOD, 1, 6))) AS HS_ADI2, REPLACE(REPLACE(REPLACE(ACIKLAMA, 'Þ', 'Ş'), 'Ý', 'İ'), 'Ð', 'G') AS ACIKLAMA, TUTAR
FROM            dbo.TBLMUHFIS AS M
WHERE        (HES_KOD IN
                             (SELECT        HESAP_KODU
                               FROM            dbo.TBLMUPLAN AS TBLMUPLAN_1
                               WHERE        (HS_BLKZ = 'I')))");
            #endregion

  

            #region ZZZZ_PLASIYER_SATIS
             Sql(@"Create   VIEW [dbo].[ZZZZ_PLASIYER_SATIS]
AS
SELECT        dbo.TBLFATUIRS.TARIH, dbo.TBLFATUIRS.GENELTOPLAM AS FTGENELTOP, CASE WHEN STHAR_KDV = 0 THEN (dbo.TBLSTHAR.STHAR_GCMIK * dbo.TBLSTHAR.STHAR_NF) 
                         ELSE (dbo.TBLSTHAR.STHAR_GCMIK * dbo.TBLSTHAR.STHAR_NF) * STHAR_KDV / 100 + (dbo.TBLSTHAR.STHAR_GCMIK * dbo.TBLSTHAR.STHAR_NF) END AS GENELTOPLAM, 
                         REPLACE(REPLACE(REPLACE(dbo.TBLSTSABIT.STOK_ADI, 'Ý', 'I'), 'Ð', 'G'), 'Þ', 'S') AS STOK_ADI, REPLACE(REPLACE(REPLACE(dbo.TBLSTSABIT.GRUP_KODU, 'Ý', 'I'), 'Ð', 'G'), 'Þ', 'S') AS GRUP_KODU, 
                         REPLACE(REPLACE(REPLACE(dbo.TBLCASABIT.CARI_ISIM, 'Ý', 'I'), 'Ð', 'G'), 'Þ', 'S') AS CARI_ISIM, REPLACE(REPLACE(REPLACE(dbo.TBLCASABIT.CARI_IL, 'Ý', 'I'), 'Ð', 'G'), 'Þ', 'S') AS CARI_IL, 
                         REPLACE(REPLACE(REPLACE(dbo.TBLCARIPLASIYER.PLASIYER_ACIKLAMA, 'Ý', 'I'), 'Ð', 'G'), 'Þ', 'S') AS PLASIYER_ACIKLAMA, dbo.TBLSTHAR.STHAR_GCMIK
FROM            dbo.TBLFATUIRS INNER JOIN
                         dbo.TBLSTHAR ON dbo.TBLFATUIRS.FATIRS_NO = dbo.TBLSTHAR.FISNO INNER JOIN
                         dbo.TBLCASABIT ON dbo.TBLFATUIRS.CARI_KODU = dbo.TBLCASABIT.CARI_KOD INNER JOIN
                         dbo.TBLSTSABIT ON dbo.TBLSTHAR.STOK_KODU = dbo.TBLSTSABIT.STOK_KODU INNER JOIN
                         dbo.TBLCARIPLASIYER ON dbo.TBLSTHAR.PLASIYER_KODU = dbo.TBLCARIPLASIYER.PLASIYER_KODU
WHERE        (dbo.TBLFATUIRS.TIPI = '2') AND (dbo.TBLFATUIRS.FTIRSIP = '1') AND (dbo.TBLSTHAR.STHAR_FTIRSIP = '1') AND (dbo.TBLSTHAR.STHAR_GCKOD = 'C')
");
            #endregion


            #region BSD_SIPATRA
            Sql(@"CREATE VIEW [dbo].[BSD_SIPATRA]
AS
SELECT        dbo.TBLSTSABIT.STOK_ADI, dbo.TBLSIPATRA.*, dbo.TBLSIPATRA.FISNO AS FATIRS_NO
FROM            dbo.TBLSIPATRA LEFT OUTER JOIN
                         dbo.TBLSTSABIT ON dbo.TBLSIPATRA.STOK_KODU = dbo.TBLSTSABIT.STOK_KODU");
            #endregion

            #region BSD_VW_ISEMIRLERI
              Sql(@"CREATE VIEW [dbo].[BSD_VW_ISEMIRLERI]
AS
SELECT        dbo.TBLSTSABIT.STOK_ADI, dbo.TBLISEMRIEK.*, dbo.TBLISEMRI.*
FROM            dbo.TBLISEMRI LEFT OUTER JOIN
                         dbo.TBLSTSABIT ON dbo.TBLISEMRI.STOK_KODU = dbo.TBLSTSABIT.STOK_KODU LEFT OUTER JOIN
                         dbo.TBLISEMRIEK ON dbo.TBLISEMRI.ISEMRINO = dbo.TBLISEMRIEK.ISEMRI");
            #endregion

            #region [ZZ_BANKA_HESAP_HAR]
            Sql(@"CREATE VIEW [dbo].[ZZ_BANKA_HESAP_HAR]
AS
SELECT        TOP (100) PERCENT
                             (SELECT        (SELECT        REPLACE(REPLACE(REPLACE(BANKAADI, 'Ý', 'İ'), 'Ð', 'Ğ'), 'Þ', 'Ş') AS BANKAADI
                                                          FROM            dbo.TBLBNKSABIT
                                                          WHERE        (NETBANKAKODU = T5.NETBANKAKODU)) AS Expr1
                               FROM            dbo.TBLBNKHESSABIT AS T5
                               WHERE        (NETHESKODU = T1.NETHESKODU)) AS BankaAdi, (CASE
                             (SELECT        HESAPTIPI
                               FROM            TBLBNKHESSABIT
                               WHERE        NETHESKODU = T1.NETHESKODU) 
                         WHEN 0 THEN '0-Vadesiz_Mevduat' WHEN 1 THEN '1-Vadeli_Mevduat' WHEN 2 THEN '2-Repo' WHEN 3 THEN '3-Teminat_Cekleri' WHEN 4 THEN '4-Teminat_Senetleri' WHEN 5 THEN '5-Tahsil_Cekleri' WHEN 6 THEN '6-Tahsil_Senetleri'
                          WHEN 7 THEN '7-Nakit_Kredi_BorcluCariKrediRotatif' WHEN 8 THEN '8-Nakit_Kredi_Spot' WHEN 9 THEN '9-Nakit_Kredi_Iskonto_Istira' WHEN 10 THEN '10-GayriNakdiKredi_TeminatMektubu' WHEN 11 THEN '11-GayriNakdiKredi_HariciGaranti'
                          WHEN 12 THEN '12-GayriNakdiKredi_IthalatAkreditifi' WHEN 13 THEN '13-GayriNakdiKredi_KabulVeAval' WHEN 14 THEN '14-KrediKartiHesabi_Pos' WHEN 15 THEN '15-Taksitli_Kredi' WHEN 16 THEN '16-Uzun_VadeliKredi' WHEN
                          17 THEN '17-Borc_Cekleri' WHEN 18 THEN '18-Borc_Senetleri' END) AS HesapTipi, NETHESKODU AS BankaHesKodu,
                             (SELECT        REPLACE(REPLACE(REPLACE(ACIKLAMA, 'Ý', 'İ'), 'Ð', 'Ğ'), 'Þ', 'Ş') AS Expr1
                               FROM            dbo.TBLBNKHESSABIT
                               WHERE        (NETHESKODU = T1.NETHESKODU)) AS HesapAdi, TARIH, BELGENO, 
                         (CASE HARTURU WHEN 0 THEN '0-Devir' WHEN 2 THEN '2-CariHavale' WHEN 3 THEN '3-BankaHavale' WHEN 4 THEN '4-Virman' WHEN 5 THEN '5-Faiz' WHEN 6 THEN '6-Masraf' END) AS HareketTuru, 
                         REPLACE(REPLACE(REPLACE(ACIKLAMA, 'Ý', 'İ'), 'Ð', 'Ğ'), 'Þ', 'Ş') AS ACIKLAMA, (CASE BA WHEN 'B' THEN TUTAR ELSE 0 END) AS Borc, (CASE BA WHEN 'A' THEN TUTAR ELSE 0 END) AS Alacak, 
                         (CASE WHEN T1.DOVIZTIPI = 0 THEN 'TL' ELSE
                             (SELECT        ISIM
                               FROM            NETSIS..KUR
                               WHERE        SIRA = T1.DOVIZTIPI) END) AS KurCinsi, (CASE WHEN DOVIZTUTAR <> 0 THEN T1.TUTAR / DOVIZTUTAR ELSE 0 END) AS Kur, (CASE BA WHEN 'B' THEN DOVIZTUTAR WHEN 'A' THEN - DOVIZTUTAR END) 
                         AS DovizTutari, PLASIYERKODU AS PlaKodu,
                             (SELECT        PLASIYER_ACIKLAMA
                               FROM            dbo.TBLCARIPLASIYER
                               WHERE        (PLASIYER_KODU = T1.PLASIYERKODU)) AS PlasiyerAdi,
                             (SELECT DISTINCT FISNO
                               FROM            dbo.TBLMUHFIS
                               WHERE        (ENTEGREFKEY = T1.ENTEGREFKEY)) AS MuhFisNo, KAYITYAPANKUL AS Kaydeden, KAYITTARIHI, NEWID() AS ID, VADETARIH,
                             (SELECT        (SELECT        REPLACE(REPLACE(REPLACE(CARI_ISIM, 'Ý', 'İ'), 'Ð', 'Ğ'), 'Þ', 'Ş') AS Expr1
                                                          FROM            dbo.TBLCASABIT
                                                          WHERE        (CARI_KOD = HR.SC_VERILENK)) AS CariiSim
                               FROM            dbo.TBLBCEK AS HR
                               WHERE        (SC_NO = T1.BELGENO)) AS CARI_ISIM
FROM            dbo.TBLBNKHESTRA AS T1
ORDER BY BankaHesKodu, TARIH");
            #endregion

            #region BOŞ
            //  Sql(@"");
            #endregion

            #region BOŞ
            //  Sql(@"");
            #endregion

            #region BOŞ
            //  Sql(@"");
            #endregion

            #region BOŞ
            //  Sql(@"");
            #endregion

            #region BOŞ
            //  Sql(@"");
            #endregion
        }

        public override void Down()
        {
            Sql("drop view BSD_VW_CEKSEN_SONISLEM");
            Sql("drop view ZZ_BSD_VW_DEPOBAKIYE");
            Sql("drop view ZZ_BSD_VW_SIPARIS");
            Sql("drop view ZZZ_CARI_RAPORU");
            Sql("drop view ZZ_BSD_VW_SATICI_SIP");
            Sql("drop PROCEDURE  BSD_RAPOR_DEPO_SIPARIS_DURUM");
            Sql("drop view BSD_TEKLIF_STOK");
            Sql("drop view BSD_SIPANA");
            Sql("drop view BSD_SIPARIS_TESLIM_STOK_ANA");
            Sql("drop view BSD_SIPARIS_TESLIM_STOK");
            Sql("drop view BSD_SATIS_TEKLIF");
            Sql("drop view BSD_SON_GIRIS_FIYATLARI");
            Sql("drop view BSD_ODEME_PLANI");
            Sql("drop view BSD_VW_ISEMIRLERI");
            Sql("drop view ZZZ_BANK_BAKIYE");
            Sql("drop view ZZZ_STOK_HAR_AYRINTI");
            Sql("drop view ZZZ_FATURASB");
            Sql("drop view ZZZ_CARI_EKSTRE");
            Sql("drop view ZZZ_KASAHAR");
            Sql("drop view ZZZ_MUH_GIDER");
            Sql("drop view ZZZZ_PLASIYER_SATIS");
            Sql("drop view BSD_SIPATRA");
            Sql("drop view BSD_VW_ISEMIRLERI");
            Sql("drop view ZZ_BANKA_HESAP_HAR");
        }
    }
}
